

const VoicemailBoxFormSchema = {
    "title": "",
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "title": "Title",
            "attr": {
                "maxlength": "120"
            },
            "maxLength": "120",
            "propertyOrder": 1
        },
        "business_name": {
            "type": "string",
            "title": "Business Name",
            "propertyOrder": 2
        },
        "business_category": {
            "enum": [],
            "enum_titles": [],
            "type": "string",
            "title": "Business Category",
            "attr": {
                "data-plugin-select2": true
            },
            "propertyOrder": 3
        },
        "first_name": {
            "type": "string",
            "title": "First Name",
            "propertyOrder": 4
        },
        "last_name": {
            "type": "string",
            "title": "Last Name",
            "propertyOrder": 5
        },
        "sic_code": {
            "enum": [
                "0100",
                "0200",
                "0700",
                "0800",
                "0900",
                "1000",
                "1040",
                "1090",
                "1220",
                "1221",
                "1311",
                "1381",
                "1382",
                "1389",
                "1400",
                "1520",
                "1531",
                "1540",
                "1600",
                "1623",
                "1629",
                "1700",
                "1731",
                "2000",
                "2011",
                "2013",
                "2015",
                "2020",
                "2024",
                "2030",
                "2033",
                "2040",
                "2050",
                "2052",
                "2060",
                "2070",
                "2080",
                "2082",
                "2086",
                "2090",
                "2092",
                "2100",
                "2111",
                "2200",
                "2211",
                "2221",
                "2250",
                "2253",
                "2273",
                "2300",
                "2320",
                "2330",
                "2340",
                "2390",
                "2400",
                "2421",
                "2430",
                "2451",
                "2452",
                "2510",
                "2511",
                "2520",
                "2522",
                "2531",
                "2540",
                "2590",
                "2600",
                "2611",
                "2621",
                "2631",
                "2650",
                "2670",
                "2673",
                "2711",
                "2721",
                "2731",
                "2732",
                "2741",
                "2750",
                "2761",
                "2771",
                "2780",
                "2790",
                "2800",
                "2810",
                "2820",
                "2821",
                "2833",
                "2834",
                "2835",
                "2836",
                "2840",
                "2842",
                "2844",
                "2851",
                "2860",
                "2870",
                "2890",
                "2891",
                "2911",
                "2950",
                "2990",
                "3011",
                "3021",
                "3050",
                "3060",
                "3080",
                "3081",
                "3086",
                "3089",
                "3100",
                "3140",
                "3211",
                "3220",
                "3221",
                "3231",
                "3241",
                "3250",
                "3260",
                "3270",
                "3272",
                "3281",
                "3290",
                "3310",
                "3312",
                "3317",
                "3320",
                "3330",
                "3334",
                "3341",
                "3350",
                "3357",
                "3360",
                "3390",
                "3411",
                "3412",
                "3420",
                "3430",
                "3433",
                "3440",
                "3442",
                "3443",
                "3444",
                "3448",
                "3451",
                "3452",
                "3460",
                "3470",
                "3480",
                "3490",
                "3510",
                "3523",
                "3524",
                "3530",
                "3531",
                "3532",
                "3533",
                "3537",
                "3540",
                "3541",
                "3550",
                "3555",
                "3559",
                "3560",
                "3561",
                "3562",
                "3564",
                "3567",
                "3569",
                "3570",
                "3571",
                "3572",
                "3575",
                "3576",
                "3577",
                "3578",
                "3579",
                "3580",
                "3585",
                "3590",
                "3600",
                "3612",
                "3613",
                "3620",
                "3621",
                "3630",
                "3634",
                "3640",
                "3651",
                "3652",
                "3661",
                "3663",
                "3669",
                "3670",
                "3672",
                "3674",
                "3677",
                "3678",
                "3679",
                "3690",
                "3695",
                "3711",
                "3713",
                "3714",
                "3715",
                "3716",
                "3720",
                "3721",
                "3724",
                "3728",
                "3730",
                "3743",
                "3751",
                "3760",
                "3790",
                "3812",
                "3821",
                "3822",
                "3823",
                "3824",
                "3825",
                "3826",
                "3827",
                "3829",
                "3841",
                "3842",
                "3843",
                "3844",
                "3845",
                "3851",
                "3861",
                "3873",
                "3910",
                "3911",
                "3931",
                "3942",
                "3944",
                "3949",
                "3950",
                "3960",
                "3990",
                "4011",
                "4013",
                "4100",
                "4210",
                "4213",
                "4220",
                "4231",
                "4400",
                "4412",
                "4512",
                "4513",
                "4522",
                "4581",
                "4610",
                "4700",
                "4731",
                "4812",
                "4813",
                "4822",
                "4832",
                "4833",
                "4841",
                "4899",
                "4900",
                "4911",
                "4922",
                "4923",
                "4924",
                "4931",
                "4932",
                "4941",
                "4950",
                "4953",
                "4955",
                "4961",
                "4991",
                "5000",
                "5010",
                "5013",
                "5020",
                "5030",
                "5031",
                "5040",
                "5045",
                "5047",
                "5050",
                "5051",
                "5063",
                "5064",
                "5065",
                "5070",
                "5072",
                "5080",
                "5082",
                "5084",
                "5090",
                "5094",
                "5099",
                "5110",
                "5122",
                "5130",
                "5140",
                "5141",
                "5150",
                "5160",
                "5171",
                "5172",
                "5180",
                "5190",
                "5200",
                "5211",
                "5271",
                "5311",
                "5331",
                "5399",
                "5400",
                "5411",
                "5412",
                "5500",
                "5531",
                "5551",
                "5600",
                "5621",
                "5651",
                "5661",
                "5700",
                "5712",
                "5731",
                "5734",
                "5735",
                "5810",
                "5812",
                "5900",
                "5912",
                "5940",
                "5944",
                "5945",
                "5960",
                "5961",
                "5990",
                "6012",
                "6021",
                "6022",
                "6029",
                "6035",
                "6036",
                "6099",
                "6111",
                "6141",
                "6153",
                "6159",
                "6162",
                "6163",
                "6172",
                "6189",
                "6199",
                "6200",
                "6211",
                "6221",
                "6282",
                "6311",
                "6321",
                "6324",
                "6331",
                "6351",
                "6361",
                "6399",
                "6411",
                "6500",
                "6510",
                "6512",
                "6513",
                "6519",
                "6531",
                "6532",
                "6552",
                "6770",
                "6792",
                "6794",
                "6795",
                "6798",
                "6799",
                "7000",
                "7011",
                "7200",
                "7310",
                "7311",
                "7320",
                "7330",
                "7331",
                "7334",
                "7340",
                "7350",
                "7359",
                "7361",
                "7363",
                "7370",
                "7371",
                "7372",
                "7373",
                "7374",
                "7377",
                "7380",
                "7381",
                "7384",
                "7385",
                "7389",
                "7500",
                "7510",
                "7600",
                "7812",
                "7819",
                "7822",
                "7829",
                "7830",
                "7841",
                "7900",
                "7948",
                "7990",
                "7994",
                "7995",
                "7996",
                "7997",
                "8000",
                "8011",
                "8050",
                "8051",
                "8060",
                "8062",
                "8071",
                "8082",
                "8090",
                "8093",
                "8111",
                "8200",
                "8300",
                "8351",
                "8600",
                "8700",
                "8711",
                "8731",
                "8734",
                "8741",
                "8742",
                "8744",
                "8748",
                "8880",
                "8888",
                "8900",
                "9721",
                "9995"
            ],
            "enum_titles": [
                "0100 - AGRICULTURAL PRODUCTION CROPS",
                "0200 - AGRICULTURAL PROD LIVESTOCK AND ANIMAL SPECIALTIES",
                "0700 - AGRICULTURAL SERVICES",
                "0800 - FORESTRY",
                "0900 - FISHING HUNTING AND TRAPPING",
                "1000 - METAL MINING",
                "1040 - GOLD AND SILVER ORES",
                "1090 - MISCELLANEOUS METAL ORES",
                "1220 - BITUMINOUS COAL AND LIGNITE MINING",
                "1221 - BITUMINOUS COAL AND LIGNITE SURFACE MINING",
                "1311 - CRUDE PETROLEUM AND NATURAL GAS",
                "1381 - DRILLING OIL AND GAS WELLS",
                "1382 - OIL AND GAS FIELD EXPLORATION SERVICES",
                "1389 - OIL AND GAS FIELD SERVICES NEC",
                "1400 - MINING AND QUARRYING OF NONMETALLIC MINERALS NO FUELS",
                "1520 - GENERAL BLDG CONTRACTORS RESIDENTIAL BLDGS",
                "1531 - OPERATIVE BUILDERS",
                "1540 - GENERAL BLDG CONTRACTORS NONRESIDENTIAL BLDGS",
                "1600 - HEAVY CONSTRUCTION OTHER THAN BLDG CONST CONTRACTORS",
                "1623 - WATER SEWER PIPELINE COMM AND POWER LINE CONSTRUCTION",
                "1629 - HEAVY CONSTRUCTION NOT ELSEWHERE CLASSIFIED",
                "1700 - CONSTRUCTION SPECIAL TRADE CONTRACTORS",
                "1731 - ELECTRICAL WORK",
                "2000 - FOOD AND KINDRED PRODUCTS",
                "2011 - MEAT PACKING PLANTS",
                "2013 - SAUSAGES AND OTHER PREPARED MEAT PRODUCTS",
                "2015 - POULTRY SLAUGHTERING AND PROCESSING",
                "2020 - DAIRY PRODUCTS",
                "2024 - ICE CREAM AND FROZEN DESSERTS",
                "2030 - CANNED FROZEN AND PRESERVED FRUIT VEG AND FOOD SPECIALTIES",
                "2033 - CANNED FRUITS VEG PRESERVES JAMS AND JELLIES",
                "2040 - GRAIN MILL PRODUCTS",
                "2050 - BAKERY PRODUCTS",
                "2052 - COOKIES AND CRACKERS",
                "2060 - SUGAR AND CONFECTIONERY PRODUCTS",
                "2070 - FATS AND OILS",
                "2080 - BEVERAGES",
                "2082 - MALT BEVERAGES",
                "2086 - BOTTLED AND CANNED SOFT DRINKS AND CARBONATED WATERS",
                "2090 - MISCELLANEOUS FOOD PREPARATIONS AND KINDRED PRODUCTS",
                "2092 - PREPARED FRESH OR FROZEN FISH AND SEAFOOD",
                "2100 - TOBACCO PRODUCTS",
                "2111 - CIGARETTES",
                "2200 - TEXTILE MILL PRODUCTS",
                "2211 - BROADWOVEN FABRIC MILLS COTTON",
                "2221 - BROADWOVEN FABRIC MILLS MAN MADE FIBER AND SILK",
                "2250 - KNITTING MILLS",
                "2253 - KNIT OUTERWEAR MILLS",
                "2273 - CARPETS AND RUGS",
                "2300 - APPAREL AND OTHER FINISHED PRODS OF FABRICS AND SIMILAR MATL",
                "2320 - MENS AND BOYS FURNISHINGS WORK CLOTHING AND ALLIED GARMENTS",
                "2330 - WOMENS MISSES AND JUNIORS OUTERWEAR",
                "2340 - WOMENS MISSES CHILDRENS AND INFANTS UNDERGARMENTS",
                "2390 - MISCELLANEOUS FABRICATED TEXTILE PRODUCTS",
                "2400 - LUMBER AND WOOD PRODUCTS NO FURNITURE",
                "2421 - SAWMILLS AND PLANING MILLS GENERAL",
                "2430 - MILLWOOD VENEER PLYWOOD AND STRUCTURAL WOOD MEMBERS",
                "2451 - MOBILE HOMES",
                "2452 - PREFABRICATED WOOD BLDGS AND COMPONENTS",
                "2510 - HOUSEHOLD FURNITURE",
                "2511 - WOOD HOUSEHOLD FURNITURE NO UPHOLSTERED",
                "2520 - OFFICE FURNITURE",
                "2522 - OFFICE FURNITURE NO WOOD",
                "2531 - PUBLIC BLDG AND RELATED FURNITURE",
                "2540 - PARTITIONS SHELVG LOCKERS AND OFFICE AND STORE FIXTURES",
                "2590 - MISCELLANEOUS FURNITURE AND FIXTURES",
                "2600 - PAPERS AND ALLIED PRODUCTS",
                "2611 - PULP MILLS",
                "2621 - PAPER MILLS",
                "2631 - PAPERBOARD MILLS",
                "2650 - PAPERBOARD CONTAINERS AND BOXES",
                "2670 - CONVERTED PAPER AND PAPERBOARD PRODS NO CONTAINERSBOXES",
                "2673 - PLASTICS FOIL AND COATED PAPER BAGS",
                "2711 - NEWSPAPERS PUBLISHING OR PUBLISHING AND PRINTING",
                "2721 - PERIODICALS PUBLISHING OR PUBLISHING AND PRINTING",
                "2731 - BOOKS PUBLISHING OR PUBLISHING AND PRINTING",
                "2732 - BOOK PRINTING",
                "2741 - MISCELLANEOUS PUBLISHING",
                "2750 - COMMERCIAL PRINTING",
                "2761 - MANIFOLD BUSINESS FORMS",
                "2771 - GREETING CARDS",
                "2780 - BLANKBOOKS LOOSELEAF BINDERS AND BOOKBINDING AND RELATED WORK",
                "2790 - SERVICE INDUSTRIES FOR THE PRINTING TRADE",
                "2800 - CHEMICALS AND ALLIED PRODUCTS",
                "2810 - INDUSTRIAL INORGANIC CHEMICALS",
                "2820 - PLASTIC MATERIAL SYNTH RESINRUBBER CELLULOS NO GLASS",
                "2821 - PLASTIC MATERIALS SYNTH RESINS AND NONVULCAN ELASTOMERS",
                "2833 - MEDICINAL CHEMICALS AND BOTANICAL PRODUCTS",
                "2834 - PHARMACEUTICAL PREPARATIONS",
                "2835 - IN VITRO AND IN VIVO DIAGNOSTIC SUBSTANCES",
                "2836 - BIOLOGICAL PRODUCTS NO DIAGNOSTIC SUBSTANCES",
                "2840 - SOAP DETERGENTS CLEANING PREPARATIONS PERFUMES COSMETICS",
                "2842 - SPECIALTY CLEANING POLISHING AND SANITATION PREPARATIONS",
                "2844 - PERFUMES COSMETICS AND OTHER TOILET PREPARATIONS",
                "2851 - PAINTS VARNISHES LACQUERS ENAMELS AND ALLIED PRODS",
                "2860 - INDUSTRIAL ORGANIC CHEMICALS",
                "2870 - AGRICULTURAL CHEMICALS",
                "2890 - MISCELLANEOUS CHEMICAL PRODUCTS",
                "2891 - ADHESIVES AND SEALANTS",
                "2911 - PETROLEUM REFINING",
                "2950 - ASPHALT PAVING AND ROOFING MATERIALS",
                "2990 - MISCELLANEOUS PRODUCTS OF PETROLEUM AND COAL",
                "3011 - TIRES AND INNER TUBES",
                "3021 - RUBBER AND PLASTICS FOOTWEAR",
                "3050 - GASKETS PACKG AND SEALG DEVICES AND RUBBER AND PLASTICS HOSE",
                "3060 - FABRICATED RUBBER PRODUCTS NEC",
                "3080 - MISCELLANEOUS PLASTICS PRODUCTS",
                "3081 - UNSUPPORTED PLASTICS FILM AND SHEET",
                "3086 - PLASTICS FOAM PRODUCTS",
                "3089 - PLASTICS PRODUCTS NEC",
                "3100 - LEATHER AND LEATHER PRODUCTS",
                "3140 - FOOTWEAR NO RUBBER",
                "3211 - FLAT GLASS",
                "3220 - GLASS AND GLASSWARE PRESSED OR BLOWN",
                "3221 - GLASS CONTAINERS",
                "3231 - GLASS PRODUCTS MADE OF PURCHASED GLASS",
                "3241 - CEMENT HYDRAULIC",
                "3250 - STRUCTURAL CLAY PRODUCTS",
                "3260 - POTTERY AND RELATED PRODUCTS",
                "3270 - CONCRETE GYPSUM AND PLASTER PRODUCTS",
                "3272 - CONCRETE PRODUCTS EXCEPT BLOCK AND BRICK",
                "3281 - CUT STONE AND STONE PRODUCTS",
                "3290 - ABRASIVE ASBESTOS AND MISC NONMETALLIC MINERAL PRODS",
                "3310 - STEEL WORKS BLAST FURNACES AND ROLLING AND FINISHING MILLS",
                "3312 - STEEL WORKS BLAST FURNACES AND ROLLING MILLS COKE OVENS",
                "3317 - STEEL PIPE AND TUBES",
                "3320 - IRON AND STEEL FOUNDRIES",
                "3330 - PRIMARY SMELTING AND REFINING OF NONFERROUS METALS",
                "3334 - PRIMARY PRODUCTION OF ALUMINUM",
                "3341 - SECONDARY SMELTING AND REFINING OF NONFERROUS METALS",
                "3350 - ROLLING DRAWING AND EXTRUDING OF NONFERROUS METALS",
                "3357 - DRAWING AND INSULATING OF NONFERROUS WIRE",
                "3360 - NONFERROUS FOUNDRIES CASTINGS",
                "3390 - MISCELLANEOUS PRIMARY METAL PRODUCTS",
                "3411 - METAL CANS",
                "3412 - METAL SHIPPING BARRELS DRUMS KEGS AND PAILS",
                "3420 - CUTLERY HANDTOOLS AND GENERAL HARDWARE",
                "3430 - HEATING EQUIP EXCEPT ELEC AND WARM AIR AND PLUMBING FIXTURES",
                "3433 - HEATING EQUIPMENT EXCEPT ELECTRIC AND WARM AIR FURNACES",
                "3440 - FABRICATED STRUCTURAL METAL PRODUCTS",
                "3442 - METAL DOORS SASH FRAMES MOLDINGS AND TRIM",
                "3443 - FABRICATED PLATE WORK BOILER SHOPS",
                "3444 - SHEET METAL WORK",
                "3448 - PREFABRICATED METAL BUILDINGS AND COMPONENTS",
                "3451 - SCREW MACHINE PRODUCTS",
                "3452 - BOLTS NUTS SCREWS RIVETS AND WASHERS",
                "3460 - METAL FORGINGS AND STAMPINGS",
                "3470 - COATING ENGRAVING AND ALLIED SERVICES",
                "3480 - ORDNANCE AND ACCESSORIES NO VEHICLESGUIDED MISSILES",
                "3490 - MISCELLANEOUS FABRICATED METAL PRODUCTS",
                "3510 - ENGINES AND TURBINES",
                "3523 - FARM MACHINERY AND EQUIPMENT",
                "3524 - LAWN AND GARDEN TRACTORS AND HOME LAWN AND GARDENS EQUIP",
                "3530 - CONSTRUCTION MINING AND MATERIALS HANDLING MACHINERY AND EQUIP",
                "3531 - CONSTRUCTION MACHINERY AND EQUIP",
                "3532 - MINING MACHINERY AND EQUIP NO OIL AND GAS FIELD MACH AND EQUIP",
                "3533 - OIL AND GAS FIELD MACHINERY AND EQUIPMENT",
                "3537 - INDUSTRIAL TRUCKS TRACTORS TRAILERS AND STACKERS",
                "3540 - METALWORKG MACHINERY AND EQUIPMENT",
                "3541 - MACHINE TOOLS METAL CUTTING TYPES",
                "3550 - SPECIAL INDUSTRY MACHINERY NO METALWORKING MACHINERY",
                "3555 - PRINTING TRADES MACHINERY AND EQUIPMENT",
                "3559 - SPECIAL INDUSTRY MACHINERY NEC",
                "3560 - GENERAL INDUSTRIAL MACHINERY AND EQUIPMENT",
                "3561 - PUMPS AND PUMPING EQUIPMENT",
                "3562 - BALL AND ROLLER BEARINGS",
                "3564 - INDUSTRIAL AND COMMERCIAL FANS AND BLOWERS AND AIR PURIFYING EQUIP",
                "3567 - INDUSTRIAL PROCESS FURNACES AND OVENS",
                "3569 - GENERAL INDUSTRIAL MACHINERY AND EQUIPMENT NEC",
                "3570 - COMPUTER AND OFFICE EQUIPMENT",
                "3571 - ELECTRONIC COMPUTERS",
                "3572 - COMPUTER STORAGE DEVICES",
                "3575 - COMPUTER TERMINALS",
                "3576 - COMPUTER COMMUNICATIONS EQUIPMENT",
                "3577 - COMPUTER PERIPHERAL EQUIPMENT NEC",
                "3578 - CALCULATING AND ACCOUNTING MACHINES NO ELECTRONIC COMPUTERS",
                "3579 - OFFICE MACHINES NEC",
                "3580 - REFRIGERATION AND SERVICE INDUSTRY MACHINERY",
                "3585 - AIR COND AND WARM AIR HEATG EQUIP AND COMM AND INDL REFRIG EQUIP",
                "3590 - MISC INDUSTRIAL AND COMMERCIAL MACHINERY AND EQUIPMENT",
                "3600 - ELECTRONIC AND OTHER ELECTRICAL EQUIPMENT NO COMPUTER EQUIP",
                "3612 - POWER DISTRIBUTION AND SPECIALTY TRANSFORMERS",
                "3613 - SWITCHGEAR AND SWITCHBOARD APPARATUS",
                "3620 - ELECTRICAL INDUSTRIAL APPARATUS",
                "3621 - MOTORS AND GENERATORS",
                "3630 - HOUSEHOLD APPLIANCES",
                "3634 - ELECTRIC HOUSEWARES AND FANS",
                "3640 - ELECTRIC LIGHTING AND WIRING EQUIPMENT",
                "3651 - HOUSEHOLD AUDIO AND VIDEO EQUIPMENT",
                "3652 - PHONOGRAPH RECORDS AND PRERECORDED AUDIO TAPES AND DISKS",
                "3661 - TELEPHONE AND TELEGRAPH APPARATUS",
                "3663 - RADIO AND TV BROADCASTING AND COMMUNICATIONS EQUIPMENT",
                "3669 - COMMUNICATIONS EQUIPMENT NEC",
                "3670 - ELECTRONIC COMPONENTS AND ACCESSORIES",
                "3672 - PRINTED CIRCUIT BOARDS",
                "3674 - SEMICONDUCTORS AND RELATED DEVICES",
                "3677 - ELECTRONIC COILS TRANSFORMERS AND OTHER INDUCTORS",
                "3678 - ELECTRONIC CONNECTORS",
                "3679 - ELECTRONIC COMPONENTS NEC",
                "3690 - MISCELLANEOUS ELECTRICAL MACHINERY EQUIPMENT AND SUPPLIES",
                "3695 - MAGNETIC AND OPTICAL RECORDING MEDIA",
                "3711 - MOTOR VEHICLES AND PASSENGER CAR BODIES",
                "3713 - TRUCK AND BUS BODIES",
                "3714 - MOTOR VEHICLE PARTS AND ACCESSORIES",
                "3715 - TRUCK TRAILERS",
                "3716 - MOTOR HOMES",
                "3720 - AIRCRAFT AND PARTS",
                "3721 - AIRCRAFT",
                "3724 - AIRCRAFT ENGINES AND ENGINE PARTS",
                "3728 - AIRCRAFT PARTS AND AUXILIARY EQUIPMENT NEC",
                "3730 - SHIP AND BOAT BUILDING AND REPAIRING",
                "3743 - RAILROAD EQUIPMENT",
                "3751 - MOTORCYCLES BICYCLES AND PARTS",
                "3760 - GUIDED MISSILES AND SPACE VEHICLES AND PARTS",
                "3790 - MISCELLANEOUS TRANSPORTATION EQUIPMENT",
                "3812 - SEARCH DETECTION NAVIGATION GUIDANCE AERONAUTICAL SYS",
                "3821 - LABORATORY APPARATUS AND FURNITURE",
                "3822 - AUTO CONTROLS FOR REGULATING RESIDENTIAL AND COMML ENVIRONMENTS",
                "3823 - INDUSTRIAL INSTRUMENTS FOR MEASUREMENT DISPLAY AND CONTROL",
                "3824 - TOTALIZING FLUID METERS AND COUNTING DEVICES",
                "3825 - INSTRUMENTS FOR MEAS AND TESTING OF ELECTRICITY AND ELEC SIGNALS",
                "3826 - LABORATORY ANALYTICAL INSTRUMENTS",
                "3827 - OPTICAL INSTRUMENTS AND LENSES",
                "3829 - MEASURING AND CONTROLLING DEVICES NEC",
                "3841 - SURGICAL AND MEDICAL INSTRUMENTS AND APPARATUS",
                "3842 - ORTHOPEDIC PROSTHETIC AND SURGICAL APPLIANCES AND SUPPLIES",
                "3843 - DENTAL EQUIPMENT AND SUPPLIES",
                "3844 - X RAY APPARATUS AND TUBES AND RELATED IRRADIATION APPARATUS",
                "3845 - ELECTROMEDICAL AND ELECTROTHERAPEUTIC APPARATUS",
                "3851 - OPHTHALMIC GOODS",
                "3861 - PHOTOGRAPHIC EQUIPMENT AND SUPPLIES",
                "3873 - WATCHES CLOCKS CLOCKWORK OPERATED DEVICESPARTS",
                "3910 - JEWELRY SILVERWARE AND PLATED WARE",
                "3911 - JEWELRY PRECIOUS METAL",
                "3931 - MUSICAL INSTRUMENTS",
                "3942 - DOLLS AND STUFFED TOYS",
                "3944 - GAMES TOYS AND CHILDRENS VEHICLES NO DOLLS AND BICYCLES",
                "3949 - SPORTING AND ATHLETIC GOODS NEC",
                "3950 - PENS PENCILS AND OTHER ARTISTS MATERIALS",
                "3960 - COSTUME JEWELRY AND NOVELTIES",
                "3990 - MISCELLANEOUS MANUFACTURING INDUSTRIES",
                "4011 - RAILROADS LINE HAUL OPERATING",
                "4013 - RAILROAD SWITCHING AND TERMINAL ESTABLISHMENTS",
                "4100 - LOCAL AND SUBURBAN TRANSIT AND INTERURBAN HWY PASSENGER TRANS",
                "4210 - TRUCKING AND COURIER SERVICES NO AIR",
                "4213 - TRUCKING NO LOCAL",
                "4220 - PUBLIC WAREHOUSING AND STORAGE",
                "4231 - TERMINAL MAINTENANCE FACILITIES FOR MOTOR FREIGHT TRANSPORT",
                "4400 - WATER TRANSPORTATION",
                "4412 - DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT",
                "4512 - AIR TRANSPORTATION SCHEDULED",
                "4513 - AIR COURIER SERVICES",
                "4522 - AIR TRANSPORTATION NONSCHEDULED",
                "4581 - AIRPORTS FLYING FIELDS AND AIRPORT TERMINAL SERVICES",
                "4610 - PIPE LINES NO NATURAL GAS",
                "4700 - TRANSPORTATION SERVICES",
                "4731 - ARRANGEMENT OF TRANSPORTATION OF FREIGHT AND CARGO",
                "4812 - RADIOTELEPHONE COMMUNICATIONS",
                "4813 - TELEPHONE COMMUNICATIONS NO RADIOTELEPHONE",
                "4822 - TELEGRAPH AND OTHER MESSAGE COMMUNICATIONS",
                "4832 - RADIO BROADCASTING STATIONS",
                "4833 - TELEVISION BROADCASTING STATIONS",
                "4841 - CABLE AND OTHER PAY TELEVISION SERVICES",
                "4899 - COMMUNICATIONS SERVICES NEC",
                "4900 - ELECTRIC GAS AND SANITARY SERVICES",
                "4911 - ELECTRIC SERVICES",
                "4922 - NATURAL GAS TRANSMISSION",
                "4923 - NATURAL GAS TRANSMISSION AND DISTRIBUTION",
                "4924 - NATURAL GAS DISTRIBUTION",
                "4931 - ELECTRIC AND OTHER SERVICES COMBINED",
                "4932 - GAS AND OTHER SERVICES COMBINED",
                "4941 - WATER SUPPLY",
                "4950 - SANITARY SERVICES",
                "4953 - REFUSE SYSTEMS",
                "4955 - HAZARDOUS WASTE MANAGEMENT",
                "4961 - STEAM AND AIR CONDITIONING SUPPLY",
                "4991 - CO GENERATION SERVICES AND SMALL POWER PRODUCERS",
                "5000 - WHOLESALE DURABLE GOODS",
                "5010 - WHOLESALE MOTOR VEHICLES AND MOTOR VEHICLE PARTS AND SUPPLIES",
                "5013 - WHOLESALE MOTOR VEHICLE SUPPLIES AND NEW PARTS",
                "5020 - WHOLESALE FURNITURE AND HOME FURNISHINGS",
                "5030 - WHOLESALE LUMBER AND OTHER CONSTRUCTION MATERIALS",
                "5031 - WHOLESALE LUMBER PLYWOOD MILLWORK AND WOOD PANELS",
                "5040 - WHOLESALE PROFESSIONAL AND COMMERCIAL EQUIPMENT AND SUPPLIES",
                "5045 - WHOLESALE COMPUTERS AND PERIPHERAL EQUIPMENT AND SOFTWARE",
                "5047 - WHOLESALE MEDICAL DENTAL AND HOSPITAL EQUIPMENT AND SUPPLIES",
                "5050 - WHOLESALE METALS AND MINERALS NO PETROLEUM",
                "5051 - WHOLESALE METALS SERVICE CENTERS AND OFFICES",
                "5063 - WHOLESALE ELECTRICAL APPARATUS AND EQUIPMENT WIRING SUPPLIES",
                "5064 - WHOLESALE ELECTRICAL APPLIANCES TV AND RADIO SETS",
                "5065 - WHOLESALE ELECTRONIC PARTS AND EQUIPMENT NEC",
                "5070 - WHOLESALE HARDWARE AND PLUMBING AND HEATING EQUIPMENT AND SUPPLIES",
                "5072 - WHOLESALE HARDWARE",
                "5080 - WHOLESALE MACHINERY EQUIPMENT AND SUPPLIES",
                "5082 - WHOLESALE CONSTRUCTION AND MINING NO PETRO MACHINERY AND EQUIP",
                "5084 - WHOLESALE INDUSTRIAL MACHINERY AND EQUIPMENT",
                "5090 - WHOLESALE MISC DURABLE GOODS",
                "5094 - WHOLESALE JEWELRY WATCHES PRECIOUS STONES AND METALS",
                "5099 - WHOLESALE DURABLE GOODS NEC",
                "5110 - WHOLESALE PAPER AND PAPER PRODUCTS",
                "5122 - WHOLESALE DRUGS PROPRIETARIES AND DRUGGISTS SUNDRIES",
                "5130 - WHOLESALE APPAREL PIECE GOODS AND NOTIONS",
                "5140 - WHOLESALE GROCERIES AND RELATED PRODUCTS",
                "5141 - WHOLESALE GROCERIES GENERAL LINE MERCHANDISE",
                "5150 - WHOLESALE FARM PRODUCT RAW MATERIALS",
                "5160 - WHOLESALE CHEMICALS AND ALLIED PRODUCTS",
                "5171 - WHOLESALE PETROLEUM BULK STATIONS AND TERMINALS",
                "5172 - WHOLESALE PETROLEUM AND PETROLEUM PRODUCTS NO BULK STATIONS",
                "5180 - WHOLESALE BEER WINE AND DISTILLED ALCOHOLIC BEVERAGES",
                "5190 - WHOLESALE MISCELLANEOUS NON DURABLE GOODS",
                "5200 - RETAIL BUILDING MATERIALS HARDWARE GARDEN SUPPLY",
                "5211 - RETAIL LUMBER AND OTHER BUILDING MATERIALS DEALERS",
                "5271 - RETAIL MOBILE HOME DEALERS",
                "5311 - RETAIL DEPARTMENT STORES",
                "5331 - RETAIL VARIETY STORES",
                "5399 - RETAIL MISC GENERAL MERCHANDISE STORES",
                "5400 - RETAIL FOOD STORES",
                "5411 - RETAIL GROCERY STORES",
                "5412 - RETAIL CONVENIENCE STORES",
                "5500 - RETAIL AUTO DEALERS AND GASOLINE STATIONS",
                "5531 - RETAIL AUTO AND HOME SUPPLY STORES",
                "5551 - BOAT DEALERS",
                "5600 - RETAIL APPAREL AND ACCESSORY STORES",
                "5621 - RETAIL WOMENS CLOTHING STORES",
                "5651 - RETAIL FAMILY CLOTHING STORES",
                "5661 - RETAIL SHOE STORES",
                "5700 - RETAIL HOME FURNITURE FURNISHINGS AND EQUIPMENT STORES",
                "5712 - RETAIL FURNITURE STORES",
                "5731 - RETAIL RADIO TV AND CONSUMER ELECTRONICS STORES",
                "5734 - RETAIL COMPUTER AND COMPUTER SOFTWARE STORES",
                "5735 - RETAIL RECORD AND PRERECORDED TAPE STORES",
                "5810 - RETAIL EATING AND DRINKING PLACES",
                "5812 - RETAIL EATING PLACES",
                "5900 - RETAIL MISCELLANEOUS RETAIL",
                "5912 - RETAIL DRUG STORES AND PROPRIETARY STORES",
                "5940 - RETAIL MISCELLANEOUS SHOPPING GOODS STORES",
                "5944 - RETAIL JEWELRY STORES",
                "5945 - RETAIL HOBBY TOY AND GAME SHOPS",
                "5960 - RETAIL NONSTORE RETAILERS",
                "5961 - RETAIL CATALOG AND MAIL ORDER HOUSES",
                "5990 - RETAIL RETAIL STORES NEC",
                "6012 - PAY DAY LENDERS",
                "6021 - NATIONAL COMMERCIAL BANKS",
                "6022 - STATE COMMERCIAL BANKS",
                "6029 - COMMERCIAL BANKS NEC",
                "6035 - SAVINGS INSTITUTION FEDERALLY CHARTERED",
                "6036 - SAVINGS INSTITUTIONS NOT FEDERALLY CHARTERED",
                "6099 - FUNCTIONS RELATED TO DEPOSITORY BANKING NEC",
                "6111 - FEDERAL AND FEDERALLY SPONSORED CREDIT AGENCIES",
                "6141 - PERSONAL CREDIT INSTITUTIONS",
                "6153 - SHORT TERM BUSINESS CREDIT INSTITUTIONS",
                "6159 - MISCELLANEOUS BUSINESS CREDIT INSTITUTION",
                "6162 - MORTGAGE BANKERS AND LOAN CORRESPONDENTS",
                "6163 - LOAN BROKERS",
                "6172 - FINANCE LESSORS",
                "6189 - ASSET BACKED SECURITIES",
                "6199 - FINANCE SERVICES",
                "6200 - SECURITY AND COMMODITY BROKERS DEALERS EXCHANGES AND SERVICES",
                "6211 - SECURITY BROKERS DEALERS AND FLOTATION COMPANIES",
                "6221 - COMMODITY CONTRACTS BROKERS AND DEALERS",
                "6282 - INVESTMENT ADVICE",
                "6311 - LIFE INSURANCE",
                "6321 - ACCIDENT AND HEALTH INSURANCE",
                "6324 - HOSPITAL AND MEDICAL SERVICE PLANS",
                "6331 - FIRE MARINE AND CASUALTY INSURANCE",
                "6351 - SURETY INSURANCE",
                "6361 - TITLE INSURANCE",
                "6399 - INSURANCE CARRIERS NEC",
                "6411 - INSURANCE AGENTS BROKERS AND SERVICE",
                "6500 - REAL ESTATE",
                "6510 - REAL ESTATE OPERATORS NO DEVELOPERS AND LESSORS",
                "6512 - OPERATORS OF NONRESIDENTIAL BUILDINGS",
                "6513 - OPERATORS OF APARTMENT BUILDINGS",
                "6519 - LESSORS OF REAL PROPERTY NEC",
                "6531 - REAL ESTATE AGENTS AND MANAGERS FOR OTHERS",
                "6532 - REAL ESTATE DEALERS FOR THEIR OWN ACCOUNT",
                "6552 - LAND SUBDIVIDERS AND DEVELOPERS NO CEMETERIES",
                "6770 - BLANK CHECKS",
                "6792 - OIL ROYALTY TRADERS",
                "6794 - PATENT OWNERS AND LESSORS",
                "6795 - MINERAL ROYALTY TRADERS",
                "6798 - REAL ESTATE INVESTMENT TRUSTS",
                "6799 - INVESTORS NEC",
                "7000 - HOTELS ROOMING HOUSES CAMPS AND OTHER LODGING PLACES",
                "7011 - HOTELS AND MOTELS",
                "7200 - SERVICES PERSONAL SERVICES",
                "7310 - SERVICES ADVERTISING",
                "7311 - SERVICES ADVERTISING AGENCIES",
                "7320 - SERVICES CONSUMER CREDIT REPORTING COLLECTION AGENCIES",
                "7330 - SERVICES MAILING REPRODUCTION COMMERCIAL ART AND PHOTOGRAPHY",
                "7331 - SERVICES DIRECT MAIL ADVERTISING SERVICES",
                "7334 - SERVICES PHOTOCOPYING AND DUPLICATING SERVICES",
                "7340 - SERVICES TO DWELLINGS AND OTHER BUILDINGS",
                "7350 - SERVICES MISCELLANEOUS EQUIPMENT RENTAL AND LEASING",
                "7359 - SERVICES EQUIPMENT RENTAL AND LEASING NEC",
                "7361 - SERVICES EMPLOYMENT AGENCIES",
                "7363 - SERVICES HELP SUPPLY SERVICES",
                "7370 - SERVICES COMPUTER PROGRAMMING DATA PROCESSING ETC",
                "7371 - SERVICES COMPUTER PROGRAMMING SERVICES",
                "7372 - SERVICES PREPACKAGED SOFTWARE",
                "7373 - SERVICES COMPUTER INTEGRATED SYSTEMS DESIGN",
                "7374 - SERVICES COMPUTER PROCESSING AND DATA PREPARATION",
                "7377 - SERVICES COMPUTER RENTAL AND LEASING",
                "7380 - SERVICES MISCELLANEOUS BUSINESS SERVICES",
                "7381 - SERVICES DETECTIVE GUARD AND ARMORED CAR SERVICES",
                "7384 - SERVICES PHOTOFINISHING LABORATORIES",
                "7385 - SERVICES TELEPHONE INTERCONNECT SYSTEMS",
                "7389 - SERVICES BUSINESS SERVICES NEC",
                "7500 - SERVICES AUTOMOTIVE REPAIR SERVICES AND PARKING",
                "7510 - SERVICES AUTO RENTAL AND LEASING NO DRIVERS",
                "7600 - SERVICES MISCELLANEOUS REPAIR SERVICES",
                "7812 - SERVICES MOTION PICTURE AND VIDEO TAPE PRODUCTION",
                "7819 - SERVICES ALLIED TO MOTION PICTURE PRODUCTION",
                "7822 - SERVICES MOTION PICTURE AND VIDEO TAPE DISTRIBUTION",
                "7829 - SERVICES ALLIED TO MOTION PICTURE DISTRIBUTION",
                "7830 - SERVICES MOTION PICTURE THEATERS",
                "7841 - SERVICES VIDEO TAPE RENTAL",
                "7900 - SERVICES AMUSEMENT AND RECREATION SERVICES",
                "7948 - SERVICES RACING INCLUDING TRACK OPERATION",
                "7990 - SERVICES MISCELLANEOUS AMUSEMENT AND RECREATION",
                "7994 - SERVICES VIDEO GAME ARCADES",
                "7995 - SERVICES GAMBLING TRANSACTIONS",
                "7996 - SERVICES AMUSEMENT PARKS",
                "7997 - SERVICES MEMBERSHIP SPORTS AND RECREATION CLUBS",
                "8000 - SERVICES HEALTH SERVICES",
                "8011 - SERVICES OFFICES AND CLINICS OF DOCTORS OF MEDICINE",
                "8050 - SERVICES NURSING AND PERSONAL CARE FACILITIES",
                "8051 - SERVICES SKILLED NURSING CARE FACILITIES",
                "8060 - SERVICES HOSPITALS",
                "8062 - SERVICES GENERAL MEDICAL AND SURGICAL HOSPITALS NEC",
                "8071 - SERVICES MEDICAL LABORATORIES",
                "8082 - SERVICES HOME HEALTH CARE SERVICES",
                "8090 - SERVICES MISC HEALTH AND ALLIED SERVICES NEC",
                "8093 - SERVICES SPECIALTY OUTPATIENT FACILITIES NEC",
                "8111 - SERVICES LEGAL SERVICES",
                "8200 - SERVICES EDUCATIONAL SERVICES",
                "8300 - SERVICES SOCIAL SERVICES",
                "8351 - SERVICES CHILD DAY CARE SERVICES",
                "8600 - SERVICES MEMBERSHIP ORGANIZATIONS",
                "8700 - SERVICES ENGINEERING ACCOUNTING RESEARCH MANAGEMENT",
                "8711 - SERVICES ENGINEERING SERVICES",
                "8731 - SERVICES COMMERCIAL PHYSICAL AND BIOLOGICAL RESEARCH",
                "8734 - SERVICES TESTING LABORATORIES",
                "8741 - SERVICES MANAGEMENT SERVICES",
                "8742 - SERVICES MANAGEMENT CONSULTING SERVICES",
                "8744 - SERVICES FACILITIES SUPPORT MANAGEMENT SERVICES",
                "8748 - BUSINESS CONSULTING SERVICES NOT ELSEWHERE CLASSIFIED",
                "8880 - AMERICAN DEPOSITARY RECEIPTS",
                "8888 - FOREIGN GOVERNMENTS",
                "8900 - SERVICES SERVICES NEC",
                "9721 - INTERNATIONAL AFFAIRS",
                "9995 - NON OPERATING ESTABLISHMENTS"
            ],
            "type": "string",
            "title": "SIC Code",
            "attr": {
                "data-plugin-select2": true
            },
            "propertyOrder": 6
        },
        "address1": {
            "type": "string",
            "title": "Address Line 1",
            "attr": {
                "maxlength": "100"
            },
            "maxLength": "100",
            "propertyOrder": 7
        },
        "address2": {
            "type": "string",
            "title": "Address Line 2",
            "attr": {
                "maxlength": "100"
            },
            "maxLength": "100",
            "propertyOrder": 8
        },
        "city": {
            "type": "string",
            "title": "City",
            "attr": {
                "maxlength": "50"
            },
            "maxLength": "50",
            "propertyOrder": 9
        },
        "state": {
            "type": "string",
            "title": "State/Province",
            "attr": {
                "maxlength": "40"
            },
            "maxLength": "40",
            "propertyOrder": 10
        },
        "postalCode": {
            "type": "string",
            "title": "Postal/Zip Code",
            "attr": {
                "maxlength": "10"
            },
            "maxLength": "10",
            "propertyOrder": 11
        },
        "country": {
            "enum": [
                "AF",
                "AX",
                "AL",
                "DZ",
                "AS",
                "AD",
                "AO",
                "AI",
                "AQ",
                "AG",
                "AR",
                "AM",
                "AW",
                "AU",
                "AT",
                "AZ",
                "BS",
                "BH",
                "BD",
                "BB",
                "BY",
                "BE",
                "BZ",
                "BJ",
                "BM",
                "BT",
                "BO",
                "BA",
                "BW",
                "BV",
                "BR",
                "IO",
                "VG",
                "BN",
                "BG",
                "BF",
                "BI",
                "KH",
                "CM",
                "CA",
                "CV",
                "BQ",
                "KY",
                "CF",
                "TD",
                "CL",
                "CN",
                "CX",
                "CC",
                "CO",
                "KM",
                "CG",
                "CD",
                "CK",
                "CR",
                "CI",
                "HR",
                "CU",
                "CW",
                "CY",
                "CZ",
                "DK",
                "DJ",
                "DM",
                "DO",
                "EC",
                "EG",
                "SV",
                "GQ",
                "ER",
                "EE",
                "SZ",
                "ET",
                "FK",
                "FO",
                "FJ",
                "FI",
                "FR",
                "GF",
                "PF",
                "TF",
                "GA",
                "GM",
                "GE",
                "DE",
                "GH",
                "GI",
                "GR",
                "GL",
                "GD",
                "GP",
                "GU",
                "GT",
                "GG",
                "GN",
                "GW",
                "GY",
                "HT",
                "HM",
                "HN",
                "HK",
                "HU",
                "IS",
                "IN",
                "ID",
                "IR",
                "IQ",
                "IE",
                "IM",
                "IL",
                "IT",
                "JM",
                "JP",
                "JE",
                "JO",
                "KZ",
                "KE",
                "KI",
                "KW",
                "KG",
                "LA",
                "LV",
                "LB",
                "LS",
                "LR",
                "LY",
                "LI",
                "LT",
                "LU",
                "MO",
                "MG",
                "MW",
                "MY",
                "MV",
                "ML",
                "MT",
                "MH",
                "MQ",
                "MR",
                "MU",
                "YT",
                "MX",
                "FM",
                "MD",
                "MC",
                "MN",
                "ME",
                "MS",
                "MA",
                "MZ",
                "MM",
                "NA",
                "NR",
                "NP",
                "NL",
                "NC",
                "NZ",
                "NI",
                "NE",
                "NG",
                "NU",
                "NF",
                "KP",
                "MK",
                "MP",
                "NO",
                "OM",
                "PK",
                "PW",
                "PS",
                "PA",
                "PG",
                "PY",
                "PE",
                "PH",
                "PN",
                "PL",
                "PT",
                "PR",
                "QA",
                "RE",
                "RO",
                "RU",
                "RW",
                "WS",
                "SM",
                "ST",
                "SA",
                "SN",
                "RS",
                "SC",
                "SL",
                "SG",
                "SX",
                "SK",
                "SI",
                "SB",
                "SO",
                "ZA",
                "GS",
                "KR",
                "SS",
                "ES",
                "LK",
                "BL",
                "SH",
                "KN",
                "LC",
                "MF",
                "PM",
                "VC",
                "SD",
                "SR",
                "SJ",
                "SE",
                "CH",
                "SY",
                "TW",
                "TJ",
                "TZ",
                "TH",
                "TL",
                "TG",
                "TK",
                "TO",
                "TT",
                "TN",
                "TR",
                "TM",
                "TC",
                "TV",
                "UM",
                "VI",
                "UG",
                "UA",
                "AE",
                "GB",
                "US",
                "UY",
                "UZ",
                "VU",
                "VA",
                "VE",
                "VN",
                "WF",
                "EH",
                "YE",
                "ZM",
                "ZW"
            ],
            "enum_titles": [
                "Afghanistan",
                "Åland Islands",
                "Albania",
                "Algeria",
                "American Samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antarctica",
                "Antigua & Barbuda",
                "Argentina",
                "Armenia",
                "Aruba",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Benin",
                "Bermuda",
                "Bhutan",
                "Bolivia",
                "Bosnia & Herzegovina",
                "Botswana",
                "Bouvet Island",
                "Brazil",
                "British Indian Ocean Territory",
                "British Virgin Islands",
                "Brunei",
                "Bulgaria",
                "Burkina Faso",
                "Burundi",
                "Cambodia",
                "Cameroon",
                "Canada",
                "Cape Verde",
                "Caribbean Netherlands",
                "Cayman Islands",
                "Central African Republic",
                "Chad",
                "Chile",
                "China",
                "Christmas Island",
                "Cocos (Keeling) Islands",
                "Colombia",
                "Comoros",
                "Congo - Brazzaville",
                "Congo - Kinshasa",
                "Cook Islands",
                "Costa Rica",
                "Côte d’Ivoire",
                "Croatia",
                "Cuba",
                "Curaçao",
                "Cyprus",
                "Czechia",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Eswatini",
                "Ethiopia",
                "Falkland Islands",
                "Faroe Islands",
                "Fiji",
                "Finland",
                "France",
                "French Guiana",
                "French Polynesia",
                "French Southern Territories",
                "Gabon",
                "Gambia",
                "Georgia",
                "Germany",
                "Ghana",
                "Gibraltar",
                "Greece",
                "Greenland",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guernsey",
                "Guinea",
                "Guinea-Bissau",
                "Guyana",
                "Haiti",
                "Heard & McDonald Islands",
                "Honduras",
                "Hong Kong SAR China",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran",
                "Iraq",
                "Ireland",
                "Isle of Man",
                "Israel",
                "Italy",
                "Jamaica",
                "Japan",
                "Jersey",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Kuwait",
                "Kyrgyzstan",
                "Laos",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macao SAR China",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall Islands",
                "Martinique",
                "Mauritania",
                "Mauritius",
                "Mayotte",
                "Mexico",
                "Micronesia",
                "Moldova",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Morocco",
                "Mozambique",
                "Myanmar (Burma)",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands",
                "New Caledonia",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "Niue",
                "Norfolk Island",
                "North Korea",
                "North Macedonia",
                "Northern Mariana Islands",
                "Norway",
                "Oman",
                "Pakistan",
                "Palau",
                "Palestinian Territories",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Pitcairn Islands",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Qatar",
                "Réunion",
                "Romania",
                "Russia",
                "Rwanda",
                "Samoa",
                "San Marino",
                "São Tomé & Príncipe",
                "Saudi Arabia",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Sint Maarten",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Georgia & South Sandwich Islands",
                "South Korea",
                "South Sudan",
                "Spain",
                "Sri Lanka",
                "St. Barthélemy",
                "St. Helena",
                "St. Kitts & Nevis",
                "St. Lucia",
                "St. Martin",
                "St. Pierre & Miquelon",
                "St. Vincent & Grenadines",
                "Sudan",
                "Suriname",
                "Svalbard & Jan Mayen",
                "Sweden",
                "Switzerland",
                "Syria",
                "Taiwan",
                "Tajikistan",
                "Tanzania",
                "Thailand",
                "Timor-Leste",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trinidad & Tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Turks & Caicos Islands",
                "Tuvalu",
                "U.S. Outlying Islands",
                "U.S. Virgin Islands",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United Kingdom",
                "United States",
                "Uruguay",
                "Uzbekistan",
                "Vanuatu",
                "Vatican City",
                "Venezuela",
                "Vietnam",
                "Wallis & Futuna",
                "Western Sahara",
                "Yemen",
                "Zambia",
                "Zimbabwe"
            ],
            "type": "string",
            "title": "Country",
            "attr": {
                "data-plugin-select2": true
            },
            "propertyOrder": 12
        },
        "date_of_birth": {
            "type": "date",
            "title": "Birthday",
            "propertyOrder": 13
        },
        "phone": {
            "type": "string",
            "title": "Phone",
            "help": "Enter a valid phone number.",
            "propertyOrder": 14
        },
        "alternatePhone": {
            "type": "string",
            "title": "Phone (Secondary)",
            "help": "Enter a valid phone number.",
            "propertyOrder": 15
        },
        "email": {
            "type": "string",
            "title": "Email",
            "widget": "email",
            "propertyOrder": 16
        },
        "alternateEmail": {
            "type": "string",
            "title": "Email (Secondary)",
            "widget": "email",
            "propertyOrder": 17
        },
        "website_url": {
            "type": "string",
            "title": "Website",
            "widget": "url",
            "propertyOrder": 18
        },
        "contact_source": {
            "enum": [
                "1",
                "2"
            ],
            "enum_titles": [
                "jhhgjhgj",
                "mhjhgjghjyhgjghj"
            ],
            "type": "string",
            "title": "Contact Source",
            "attr": {
                "data-plugin-select2": true
            },
            "propertyOrder": 19
        },
        "tag_names": {
            "items": {
                "type": "string",
                "enum": [],
                "enum_titles": []
            },
            "minItems": 0,
            "uniqueItems": true,
            "type": "array",
            "title": "Tag Names",
            "attr": {
                "data-plugin-select2": true
            },
            "propertyOrder": 20
        },
        "status": {
            "enum": [
                "1",
                "2",
                "3",
                "4"
            ],
            "enum_titles": [
                "Initial Contact / Interested",
                "Demo Scheduled",
                "Demo Complete",
                "Proposal Sent / Follow Up"
            ],
            "type": "string",
            "title": "Status",
            "attr": {
                "data-plugin-select2": true
            },
            "propertyOrder": 21
        }
    },
    "required": [
        "country"
    ],
    "operations": [
        {
            "title": "Edit",
            "is_standard": true,
            "method": "PATCH",
            "key": "edit",
            "route_suffix": "",
            "visible": true
        },
        {
            "title": "Delete",
            "is_standard": false,
            "key": "delete",
            "visible": true
        },
        {
            "title": "See related objects",
            "is_standard": false,
            "redirect_url": "relations/contacts/:id",
            "description": "See other objects in the system that have relations to this one.",
            "key": "link",
            "visible": false
        }
    ]
}
const VoicemailBoxTableSchema = {
    "type": "Lead",
    "columns": [
        {
            "type": "int",
            "label": "ID",
            "property_name": "id",
            "filterable": true,
            "sortable": true,
            "visible": false,
            "order": 1
        },
        {
            "type": "string",
            "label": "Title",
            "property_name": "title",
            "filterable": false,
            "sortable": false,
            "visible": true
        },
        {
            "type": "string",
            "label": "Business name",
            "property_name": "business_name",
            "filterable": true,
            "sortable": true,
            "visible": true
        },
        {
            "type": "string",
            "label": "First name",
            "property_name": "first_name",
            "filterable": true,
            "sortable": true,
            "visible": true
        },
        {
            "type": "string",
            "label": "Last name",
            "property_name": "last_name",
            "filterable": true,
            "sortable": true,
            "visible": true
        },
        {
            "type": "string",
            "label": "city",
            "property_name": "city",
            "filterable": true,
            "sortable": false,
            "visible": false
        },
        {
            "type": "string",
            "label": "state",
            "property_name": "state",
            "filterable": true,
            "sortable": false,
            "visible": false
        },
        {
            "type": "string",
            "label": "postalCode",
            "property_name": "postal_code",
            "filterable": true,
            "sortable": false,
            "visible": false
        },
        {
            "type": "string",
            "label": "country",
            "property_name": "country",
            "filterable": true,
            "sortable": false,
            "visible": false
        },
        {
            "type": "phone_number",
            "label": "Phone",
            "property_name": "phone",
            "filterable": true,
            "sortable": true,
            "visible": true
        },
        {
            "type": "phone_number",
            "label": "Alternate Phone",
            "property_name": "alternate_phone",
            "filterable": true,
            "sortable": true,
            "visible": false
        },
        {
            "type": "phone_number",
            "label": "Fax",
            "property_name": "fax",
            "filterable": false,
            "sortable": false,
            "visible": false
        },
        {
            "type": "phone_number",
            "label": "Mobile",
            "property_name": "mobile",
            "filterable": false,
            "sortable": false,
            "visible": false
        },
        {
            "type": "email",
            "label": "email",
            "property_name": "email",
            "filterable": true,
            "sortable": false,
            "visible": false
        },
        {
            "type": "email",
            "label": "alternateEmail",
            "property_name": "alternate_email",
            "filterable": true,
            "sortable": false,
            "visible": false
        },
        {
            "type": "link",
            "label": "websiteUrl",
            "property_name": "website_url",
            "filterable": false,
            "sortable": false,
            "visible": false
        },
        {
            "type": "LeadStatus",
            "label": "Lead status",
            "property_name": "status.name",
            "filterable": false,
            "sortable": false,
            "visible": true
        }
    ],
    "operations": [
        {
            "title": "Create",
            "is_standard": true,
            "method": "POST",
            "key": "create",
            "route_suffix": "",
            "visible": false
        },
        {
            "title": "Bulk delete",
            "is_standard": false,
            "key": "bulk_delete",
            "visible": false
        },
        {
            "title": "Bulk edit",
            "is_standard": false,
            "key": "bulk_edit",
            "visible": false
        },
        {
            "title": "Export",
            "is_standard": false,
            "key": "export",
            "visible": false
        },
        {
            "title": "Import",
            "is_standard": false,
            "key": "import",
            "visible": false
        }
    ],
    "size": 17,
    "polymorphic_crud_types": [],
    "primary_key": "id",
    "search": false
}
const VoicemailBoxes = {
    type: "array",
    $ref: "#/components/schemas/VoicemailBoxTableSchema",
};
module.exports = {
    VoicemailBoxFormSchema,
    VoicemailBoxTableSchema,
    VoicemailBoxes,
};