const {
  activity_category_enum,
  activity_category_enum_titles,
} = require("../../../constants/activity");
const {
  employee_enum,
  employee_enum_titles,
} = require("../../../constants/employees");

const MissingDataFormSchema = {
  properties: [],
};

const MissingDataTableSchema = {
  type: "MissingData",
  columns: [
    {
      type: "string",
      label: "Property Name",
      property_name: "information",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "link",
      label: "Missing count",
      property_name: "count",
      filterable: false,
      sortable: false,
      visible: true,
    },
  ],
  operations: [],
  size: 2,
  primary_key: "",
  search: false,
  title: "Missing Data of Employees",
};

const MissingDatas = {
  type: "array",
  $ref: "#/components/schemas/MissingDataTableSchema",
};

const AgeProfileFormSchema = {
  title: "age_profile_report_request",
  type: "object",
  properties: [],
  operations: [
    {
      title: "Edit",
      is_standard: true,
      method: "PATCH",
      key: "edit",
      route_suffix: "",
      visible: true,
    },
    {
      title: "Delete",
      is_standard: false,
      key: "delete",
      visible: true,
    },
  ],
};

const AgeProfileTableSchema = {
  type: "Employee",
  columns: [
    {
      type: "image",
      label: "Picture",
      property_name: "picture_url",
      filterable: false,
      sortable: false,
      visible: true,
      order: 1,
    },
    {
      type: "int",
      label: "ID",
      property_name: "id",
      filterable: true,
      sortable: true,
      visible: false,
      order: 1,
    },
    {
      type: "DateTime",
      label: "Terminated",
      property_name: "terminated_at",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Username",
      property_name: "user.username",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Role",
      property_name: "role_in_organization",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "bool",
      label: "Approved",
      property_name: "approved",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Name",
      property_name: "name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Second Name",
      property_name: "second_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Preferred Name",
      property_name: "preferred_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Last Name",
      property_name: "last_name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "DateTimeInterface",
      label: "Birth Date",
      property_name: "birth_date",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "SSN",
      property_name: "ssn",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Gender",
      property_name: "gender",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Marital Status",
      property_name: "marital_status",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address",
      property_name: "street1",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address 2",
      property_name: "street2",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "City",
      property_name: "city",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Province",
      property_name: "province",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Postal Code",
      property_name: "postal_code",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Country",
      property_name: "country",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Work Phone Number",
      property_name: "work_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Mobile Phone Number",
      property_name: "mobile_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Home Phone Number",
      property_name: "home_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Business Mail",
      property_name: "business_mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Mail",
      property_name: "mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Schedule",
      label: "Schedule",
      property_name: "schedule.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "boolean",
      label: "Active",
      property_name: "active",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Department",
      label: "Department",
      property_name: "department.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "JobType",
      label: "Job Type",
      property_name: "job_type.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "Shift",
      label: "Shift",
      property_name: "shift.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "status",
      label: "Status",
      property_name: "employee_approved",
      filterable: false,
      sortable: false,
      visible: true,
    },
  ],
  operations: [
    {
      title: "Create",
      is_standard: true,
      method: "POST",
      key: "create",
      route_suffix: "",
      visible: false,
    },
    {
      title: "Bulk delete",
      is_standard: false,
      key: "bulk_delete",
      visible: false,
    },
    {
      title: "Bulk edit",
      is_standard: false,
      key: "bulk_edit",
      visible: false,
    },
  ],
  size: 31,
  polymorphic_crud_types: [],
  primary_key: "id",
  search: false,
};

const AgeProfiles = {
  type: "array",
  $ref: "#/components/schemas/AgeProfileTableSchema",
};

const GenderProfileFormSchema = {
  title: "",
  type: "object",
  properties: [],
  operations: [
    {
      title: "Edit",
      is_standard: true,
      method: "PATCH",
      key: "edit",
      route_suffix: "",
      visible: true,
    },
    {
      title: "Delete",
      is_standard: false,
      key: "delete",
      visible: true,
    },
  ],
};
const GenderProfileTableSchema = {
  type: "Employee",
  columns: [
    {
      type: "image",
      label: "Picture",
      property_name: "picture_url",
      filterable: false,
      sortable: false,
      visible: true,
      order: 1,
    },
    {
      type: "int",
      label: "ID",
      property_name: "id",
      filterable: true,
      sortable: true,
      visible: false,
      order: 1,
    },
    {
      type: "DateTime",
      label: "Terminated",
      property_name: "terminated_at",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Username",
      property_name: "user.username",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Role",
      property_name: "role_in_organization",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "bool",
      label: "Approved",
      property_name: "approved",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Name",
      property_name: "name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Second Name",
      property_name: "second_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Preferred Name",
      property_name: "preferred_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Last Name",
      property_name: "last_name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "DateTimeInterface",
      label: "Birth Date",
      property_name: "birth_date",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "SSN",
      property_name: "ssn",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Gender",
      property_name: "gender",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Marital Status",
      property_name: "marital_status",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address",
      property_name: "street1",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address 2",
      property_name: "street2",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "City",
      property_name: "city",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Province",
      property_name: "province",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Postal Code",
      property_name: "postal_code",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Country",
      property_name: "country",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Work Phone Number",
      property_name: "work_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Mobile Phone Number",
      property_name: "mobile_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Home Phone Number",
      property_name: "home_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Business Mail",
      property_name: "business_mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Mail",
      property_name: "mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Schedule",
      label: "Schedule",
      property_name: "schedule.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "boolean",
      label: "Active",
      property_name: "active",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Department",
      label: "Department",
      property_name: "department.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "JobType",
      label: "Job Type",
      property_name: "job_type.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "Shift",
      label: "Shift",
      property_name: "shift.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "status",
      label: "Status",
      property_name: "employee_approved",
      filterable: false,
      sortable: false,
      visible: true,
    },
  ],
  operations: [
    {
      title: "Create",
      is_standard: true,
      method: "POST",
      key: "create",
      route_suffix: "",
      visible: false,
    },
    {
      title: "Bulk delete",
      is_standard: false,
      key: "bulk_delete",
      visible: false,
    },
    {
      title: "Bulk edit",
      is_standard: false,
      key: "bulk_edit",
      visible: false,
    },
  ],
  size: 31,
  polymorphic_crud_types: [],
  primary_key: "id",
  search: false,
};
const GenderProfiles = {
  type: "array",
  $ref: "#/components/schemas/GenderProfileTableSchema",
};

const JobHistoryFormSchema = {
  title: "",
  type: "object",
  properties: {
    start: {
      type: "date",
      title: "Start",
      propertyOrder: 1,
    },
    end: {
      type: "date",
      title: "End",
      propertyOrder: 2,
    },
  },
  required: ["start", "end"],
  operations: [
    {
      title: "Edit",
      is_standard: true,
      method: "PATCH",
      key: "edit",
      route_suffix: "",
      visible: true,
    },
    {
      title: "Delete",
      is_standard: false,
      key: "delete",
      visible: true,
    },
  ],
};

const JobHistoryTableSchema = {
  type: "Employee",
  columns: [
    {
      type: "image",
      label: "Picture",
      property_name: "picture_url",
      filterable: false,
      sortable: false,
      visible: true,
      order: 1,
    },
    {
      type: "int",
      label: "ID",
      property_name: "id",
      filterable: true,
      sortable: true,
      visible: false,
      order: 1,
    },
    {
      type: "DateTime",
      label: "Terminated",
      property_name: "terminated_at",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Username",
      property_name: "user.username",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Role",
      property_name: "role_in_organization",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "bool",
      label: "Approved",
      property_name: "approved",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Name",
      property_name: "name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Second Name",
      property_name: "second_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Preferred Name",
      property_name: "preferred_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Last Name",
      property_name: "last_name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "DateTimeInterface",
      label: "Birth Date",
      property_name: "birth_date",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "SSN",
      property_name: "ssn",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Gender",
      property_name: "gender",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Marital Status",
      property_name: "marital_status",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address",
      property_name: "street1",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address 2",
      property_name: "street2",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "City",
      property_name: "city",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Province",
      property_name: "province",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Postal Code",
      property_name: "postal_code",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Country",
      property_name: "country",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Work Phone Number",
      property_name: "work_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Mobile Phone Number",
      property_name: "mobile_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Home Phone Number",
      property_name: "home_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Business Mail",
      property_name: "business_mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Mail",
      property_name: "mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Schedule",
      label: "Schedule",
      property_name: "schedule.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "boolean",
      label: "Active",
      property_name: "active",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Department",
      label: "Department",
      property_name: "department.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "JobType",
      label: "Job Type",
      property_name: "job_type.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "Shift",
      label: "Shift",
      property_name: "shift.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "status",
      label: "Status",
      property_name: "employee_approved",
      filterable: false,
      sortable: false,
      visible: true,
    },
  ],
  operations: [
    {
      title: "Create",
      is_standard: true,
      method: "POST",
      key: "create",
      route_suffix: "",
      visible: false,
    },
    {
      title: "Bulk delete",
      is_standard: false,
      key: "bulk_delete",
      visible: false,
    },
    {
      title: "Bulk edit",
      is_standard: false,
      key: "bulk_edit",
      visible: false,
    },
  ],
  size: 31,
  polymorphic_crud_types: [],
  primary_key: "id",
  search: false,
};
const JobHistories = {
  type: "array",
  $ref: "#/components/schemas/JobHistoryTableSchema",
};

const HeadCountFormSchema = {
  title: "",
  type: "object",
  properties: {
    start: {
      type: "date",
      title: "Start",
      propertyOrder: 1,
    },
    end: {
      type: "date",
      title: "End",
      propertyOrder: 2,
    },
  },
  required: ["start", "end"],
  operations: [
    {
      title: "Edit",
      is_standard: true,
      method: "PATCH",
      key: "edit",
      route_suffix: "",
      visible: true,
    },
    {
      title: "Delete",
      is_standard: false,
      key: "delete",
      visible: true,
    },
  ],
};

const HeadCountTableSchema = {
  type: "Employee",
  columns: [
    {
      type: "image",
      label: "Picture",
      property_name: "picture_url",
      filterable: false,
      sortable: false,
      visible: true,
      order: 1,
    },
    {
      type: "int",
      label: "ID",
      property_name: "id",
      filterable: true,
      sortable: true,
      visible: false,
      order: 1,
    },
    {
      type: "DateTime",
      label: "Terminated",
      property_name: "terminated_at",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Username",
      property_name: "user.username",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Role",
      property_name: "role_in_organization",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "bool",
      label: "Approved",
      property_name: "approved",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Name",
      property_name: "name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Second Name",
      property_name: "second_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Preferred Name",
      property_name: "preferred_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Last Name",
      property_name: "last_name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "DateTimeInterface",
      label: "Birth Date",
      property_name: "birth_date",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "SSN",
      property_name: "ssn",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Gender",
      property_name: "gender",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Marital Status",
      property_name: "marital_status",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address",
      property_name: "street1",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address 2",
      property_name: "street2",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "City",
      property_name: "city",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Province",
      property_name: "province",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Postal Code",
      property_name: "postal_code",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Country",
      property_name: "country",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Work Phone Number",
      property_name: "work_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Mobile Phone Number",
      property_name: "mobile_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Home Phone Number",
      property_name: "home_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Business Mail",
      property_name: "business_mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Mail",
      property_name: "mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Schedule",
      label: "Schedule",
      property_name: "schedule.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "boolean",
      label: "Active",
      property_name: "active",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Department",
      label: "Department",
      property_name: "department.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "JobType",
      label: "Job Type",
      property_name: "job_type.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "Shift",
      label: "Shift",
      property_name: "shift.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "status",
      label: "Status",
      property_name: "employee_approved",
      filterable: false,
      sortable: false,
      visible: true,
    },
  ],
  operations: [
    {
      title: "Create",
      is_standard: true,
      method: "POST",
      key: "create",
      route_suffix: "",
      visible: false,
    },
    {
      title: "Bulk delete",
      is_standard: false,
      key: "bulk_delete",
      visible: false,
    },
    {
      title: "Bulk edit",
      is_standard: false,
      key: "bulk_edit",
      visible: false,
    },
  ],
  size: 31,
  polymorphic_crud_types: [],
  primary_key: "id",
  search: false,
};
const HeadCounts = {
  type: "array",
  $ref: "#/components/schemas/HeadCountTableSchema",
};

const TurnOverFormSchema = {
  title: "",
  type: "object",
  properties: {
    start: {
      type: "date",
      title: "Start",
      propertyOrder: 1,
    },
    end: {
      type: "date",
      title: "End",
      propertyOrder: 2,
    },
  },
  required: ["start", "end"],
  operations: [
    {
      title: "Edit",
      is_standard: true,
      method: "PATCH",
      key: "edit",
      route_suffix: "",
      visible: true,
    },
    {
      title: "Delete",
      is_standard: false,
      key: "delete",
      visible: true,
    },
  ],
};

const TurnOverTableSchema = {
  type: "Employee",
  columns: [
    {
      type: "image",
      label: "Picture",
      property_name: "picture_url",
      filterable: false,
      sortable: false,
      visible: true,
      order: 1,
    },
    {
      type: "int",
      label: "ID",
      property_name: "id",
      filterable: true,
      sortable: true,
      visible: false,
      order: 1,
    },
    {
      type: "DateTime",
      label: "Terminated",
      property_name: "terminated_at",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Username",
      property_name: "user.username",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Role",
      property_name: "role_in_organization",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "bool",
      label: "Approved",
      property_name: "approved",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Name",
      property_name: "name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Second Name",
      property_name: "second_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Preferred Name",
      property_name: "preferred_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Last Name",
      property_name: "last_name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "DateTimeInterface",
      label: "Birth Date",
      property_name: "birth_date",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "SSN",
      property_name: "ssn",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Gender",
      property_name: "gender",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Marital Status",
      property_name: "marital_status",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address",
      property_name: "street1",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address 2",
      property_name: "street2",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "City",
      property_name: "city",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Province",
      property_name: "province",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Postal Code",
      property_name: "postal_code",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Country",
      property_name: "country",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Work Phone Number",
      property_name: "work_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Mobile Phone Number",
      property_name: "mobile_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Home Phone Number",
      property_name: "home_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Business Mail",
      property_name: "business_mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Mail",
      property_name: "mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Schedule",
      label: "Schedule",
      property_name: "schedule.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "boolean",
      label: "Active",
      property_name: "active",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Department",
      label: "Department",
      property_name: "department.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "JobType",
      label: "Job Type",
      property_name: "job_type.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "Shift",
      label: "Shift",
      property_name: "shift.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "status",
      label: "Status",
      property_name: "employee_approved",
      filterable: false,
      sortable: false,
      visible: true,
    },
  ],
  operations: [
    {
      title: "Create",
      is_standard: true,
      method: "POST",
      key: "create",
      route_suffix: "",
      visible: false,
    },
    {
      title: "Bulk delete",
      is_standard: false,
      key: "bulk_delete",
      visible: false,
    },
    {
      title: "Bulk edit",
      is_standard: false,
      key: "bulk_edit",
      visible: false,
    },
  ],
  size: 31,
  polymorphic_crud_types: [],
  primary_key: "id",
  search: false,
};
const TurnOvers = {
  type: "array",
  $ref: "#/components/schemas/TurnOverTableSchema",
};

const YearOfServiceFormSchema = {
  title: "",
  type: "object",
  properties: [],
  operations: [
    {
      title: "Edit",
      is_standard: true,
      method: "PATCH",
      key: "edit",
      route_suffix: "",
      visible: true,
    },
    {
      title: "Delete",
      is_standard: false,
      key: "delete",
      visible: true,
    },
  ],
};

const YearOfServiceTableSchema = {
  type: "Employee",
  columns: [
    {
      type: "image",
      label: "Picture",
      property_name: "picture_url",
      filterable: false,
      sortable: false,
      visible: true,
      order: 1,
    },
    {
      type: "int",
      label: "ID",
      property_name: "id",
      filterable: true,
      sortable: true,
      visible: false,
      order: 1,
    },
    {
      type: "DateTime",
      label: "Terminated",
      property_name: "terminated_at",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Username",
      property_name: "user.username",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Role",
      property_name: "role_in_organization",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "bool",
      label: "Approved",
      property_name: "approved",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Name",
      property_name: "name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Second Name",
      property_name: "second_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Preferred Name",
      property_name: "preferred_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Last Name",
      property_name: "last_name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "DateTimeInterface",
      label: "Birth Date",
      property_name: "birth_date",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "SSN",
      property_name: "ssn",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Gender",
      property_name: "gender",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Marital Status",
      property_name: "marital_status",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address",
      property_name: "street1",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address 2",
      property_name: "street2",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "City",
      property_name: "city",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Province",
      property_name: "province",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Postal Code",
      property_name: "postal_code",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Country",
      property_name: "country",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Work Phone Number",
      property_name: "work_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Mobile Phone Number",
      property_name: "mobile_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Home Phone Number",
      property_name: "home_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Business Mail",
      property_name: "business_mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Mail",
      property_name: "mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Schedule",
      label: "Schedule",
      property_name: "schedule.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "boolean",
      label: "Active",
      property_name: "active",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Department",
      label: "Department",
      property_name: "department.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "JobType",
      label: "Job Type",
      property_name: "job_type.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "Shift",
      label: "Shift",
      property_name: "shift.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "status",
      label: "Status",
      property_name: "employee_approved",
      filterable: false,
      sortable: false,
      visible: true,
    },
  ],
  operations: [
    {
      title: "Create",
      is_standard: true,
      method: "POST",
      key: "create",
      route_suffix: "",
      visible: false,
    },
    {
      title: "Bulk delete",
      is_standard: false,
      key: "bulk_delete",
      visible: false,
    },
    {
      title: "Bulk edit",
      is_standard: false,
      key: "bulk_edit",
      visible: false,
    },
  ],
  size: 31,
  polymorphic_crud_types: [],
  primary_key: "id",
  search: false,
};

const YearOfServices = {
  type: "array",
  $ref: "#/components/schemas/YearOfServiceTableSchema",
};

const VacationDowntimeFormSchema = {
  title: "",
  type: "object",
  properties: {
    start: {
      type: "date",
      title: "Start",
      propertyOrder: 1,
    },
    end: {
      type: "date",
      title: "End",
      propertyOrder: 2,
    },
  },
  required: ["start", "end"],
  operations: [
    {
      title: "Edit",
      is_standard: true,
      method: "PATCH",
      key: "edit",
      route_suffix: "",
      visible: true,
    },
    {
      title: "Delete",
      is_standard: false,
      key: "delete",
      visible: true,
    },
  ],
};

const VacationDowntimeTableSchema = {
  type: "Employee",
  columns: [
    {
      type: "image",
      label: "Picture",
      property_name: "picture_url",
      filterable: false,
      sortable: false,
      visible: true,
      order: 1,
    },
    {
      type: "int",
      label: "ID",
      property_name: "id",
      filterable: true,
      sortable: true,
      visible: false,
      order: 1,
    },
    {
      type: "DateTime",
      label: "Terminated",
      property_name: "terminated_at",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Username",
      property_name: "user.username",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Role",
      property_name: "role_in_organization",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "bool",
      label: "Approved",
      property_name: "approved",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Name",
      property_name: "name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Second Name",
      property_name: "second_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Preferred Name",
      property_name: "preferred_name",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Last Name",
      property_name: "last_name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "DateTimeInterface",
      label: "Birth Date",
      property_name: "birth_date",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "SSN",
      property_name: "ssn",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Gender",
      property_name: "gender",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "string",
      label: "Marital Status",
      property_name: "marital_status",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address",
      property_name: "street1",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Address 2",
      property_name: "street2",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "City",
      property_name: "city",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Province",
      property_name: "province",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Postal Code",
      property_name: "postal_code",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "string",
      label: "Country",
      property_name: "country",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Work Phone Number",
      property_name: "work_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Mobile Phone Number",
      property_name: "mobile_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "phone_number",
      label: "Home Phone Number",
      property_name: "home_phone",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Business Mail",
      property_name: "business_mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "email",
      label: "Mail",
      property_name: "mail",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Schedule",
      label: "Schedule",
      property_name: "schedule.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "boolean",
      label: "Active",
      property_name: "active",
      filterable: false,
      sortable: false,
      visible: false,
    },
    {
      type: "Department",
      label: "Department",
      property_name: "department.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "JobType",
      label: "Job Type",
      property_name: "job_type.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "Shift",
      label: "Shift",
      property_name: "shift.name",
      filterable: false,
      sortable: false,
      visible: true,
    },
    {
      type: "status",
      label: "Status",
      property_name: "employee_approved",
      filterable: false,
      sortable: false,
      visible: true,
    },
  ],
  operations: [
    {
      title: "Create",
      is_standard: true,
      method: "POST",
      key: "create",
      route_suffix: "",
      visible: false,
    },
    {
      title: "Bulk delete",
      is_standard: false,
      key: "bulk_delete",
      visible: false,
    },
    {
      title: "Bulk edit",
      is_standard: false,
      key: "bulk_edit",
      visible: false,
    },
  ],
  size: 31,
  polymorphic_crud_types: [],
  primary_key: "id",
  search: false,
};
const VacationDowntimes = {
  type: "array",
  $ref: "#/components/schemas/VacationDowntimeTableSchema",
};

const TimeActivityTrackingPerEmployeeFormSchema = {
  title: "",
  type: "object",
  properties: {
    start: {
      type: "date",
      title: "Start",
      propertyOrder: 1,
    },
    end: {
      type: "date",
      title: "End",
      propertyOrder: 2,
    },
    employee: {
      enum: employee_enum,
      enum_titles: employee_enum_titles,
      type: "string",
      title: "Employee",
      attr: {
        "data-plugin-select2": true,
      },
      help: "Please select employee",
      propertyOrder: 3,
    },
    period: {
      title: "Period",
      type: "object",
      properties: {
        code: {
          enum: ["yearly", "monthly", "bi-weekly", "weekly", "daily", "hourly"],
          enum_titles: [
            "Yearly",
            "Monthly",
            "Bi-Weekly",
            "Weekly",
            "Daily",
            "Hourly",
          ],
          type: "string",
          title: "Select period",
          propertyOrder: 1,
        },
      },
      required: ["code"],
      attr: {
        disable_wrapper: true,
      },
      propertyOrder: 4,
    },
  },
  required: ["start", "end", "employee", "period"],
};

const TimeActivityTrackingPerEmployeeTableSchema = {
  type: "TimeTrackingPerEmployeeReportTableSchema",
  columns: [
    {
      type: "DateTime",
      label: "From",
      property_name: "from",
      filterable: true,
      sortable: true,
      visible: true,
      order: 1,
    },
    {
      type: "DateTime",
      label: "To",
      property_name: "to",
      filterable: true,
      sortable: true,
      visible: true,
      order: 2,
    },
    {
      type: "int",
      label: "Total",
      property_name: "total",
      filterable: true,
      sortable: true,
      visible: true,
      order: 99999,
    },
  ],
  operations: [],
  size: 3,
  primary_key: "",
  search: false,
};
const TimeActivityTrackingsPerEmployee = {
  type: "array",
  $ref: "#/components/schemas/TimeActivityTrackingPerEmployeeTableSchema",
};

const TimeActivityTrackingPerCategoryFormSchema = {
  title: "",
  type: "object",
  properties: {
    start: {
      type: "date",
      title: "Start",
      propertyOrder: 1,
    },
    end: {
      type: "date",
      title: "End",
      propertyOrder: 2,
    },
    activity_category: {
      enum: activity_category_enum,
      enum_titles: activity_category_enum_titles,
      type: "string",
      title: "Activity Category",
      attr: {
        resource_path: "activity-categories",
        create_button_text: "Create a new activity category",
        "data-plugin-select2": true,
      },
      help: "Please select employee",
      propertyOrder: 3,
    },
    period: {
      title: "Period",
      type: "object",
      properties: {
        code: {
          enum: ["yearly", "monthly", "bi-weekly", "weekly", "daily", "hourly"],
          enum_titles: [
            "Yearly",
            "Monthly",
            "Bi-Weekly",
            "Weekly",
            "Daily",
            "Hourly",
          ],
          type: "string",
          title: "Select period",
          propertyOrder: 1,
        },
      },
      required: ["code"],
      attr: {
        disable_wrapper: true,
      },
      propertyOrder: 4,
    },
  },
  required: ["start", "end", "activity_category", "period"],
};

const TimeActivityTrackingPerCategoryTableSchema = {
  type: "TimeTrackingPerActivityCategoryReportTableSchema",
  columns: [
    {
      type: "DateTime",
      label: "From",
      property_name: "from",
      filterable: true,
      sortable: true,
      visible: true,
      order: 1,
    },
    {
      type: "DateTime",
      label: "To",
      property_name: "to",
      filterable: true,
      sortable: true,
      visible: true,
      order: 2,
    },
  ],
  operations: [],
  size: 2,
  primary_key: "",
  search: false,
};
const TimeActivityTrackingsPerCategory = {
  type: "array",
  $ref: "#/components/schemas/TimeActivityTrackingPerCategoryTableSchema",
};

module.exports = {
  MissingDataFormSchema,
  MissingDataTableSchema,
  MissingDatas,

  AgeProfileFormSchema,
  AgeProfileTableSchema,
  AgeProfiles,

  GenderProfileFormSchema,
  GenderProfileTableSchema,
  GenderProfiles,

  JobHistoryFormSchema,
  JobHistoryTableSchema,
  JobHistories,

  HeadCountFormSchema,
  HeadCountTableSchema,
  HeadCounts,

  TurnOverFormSchema,
  TurnOverTableSchema,
  TurnOvers,

  YearOfServiceFormSchema,
  YearOfServiceTableSchema,
  YearOfServices,

  VacationDowntimeFormSchema,
  VacationDowntimeTableSchema,
  VacationDowntimes,

  TimeActivityTrackingPerEmployeeFormSchema,
  TimeActivityTrackingPerEmployeeTableSchema,
  TimeActivityTrackingsPerEmployee,

  TimeActivityTrackingPerCategoryFormSchema,
  TimeActivityTrackingPerCategoryTableSchema,
  TimeActivityTrackingsPerCategory,
};
