const backoffice = require("./backoffice");
const switchModule = require("./switch");
const employeePortal = require("./employee-portal");
const crm = require("./crm");
// const monitoring = require("./monitoring");
const pbx = require("./pbx");
const worspaceConfiguration = require("./worspace-configuration");

module.exports = {
  schemas: {
    // backoffice schemas
    // ...backoffice.Auth.schemas,
    ...backoffice.ClientUser.schemas,
    ...backoffice.UserGroup.schemas,
    ...backoffice.Role.schemas,
    ...backoffice.MailingConfiguration.schemas,
    ...backoffice.UserSelf.schemas,
    // switch schemas
    ...switchModule.MyAccount.schemas,
    ...switchModule.CallLogs.schemas,
    ...switchModule.MessageLogs.schemas,
    ...switchModule.InternalGateways.schemas,
    // employee-portal schemas
    ...employeePortal.MyAccount.schemas,
    ...employeePortal.Employees.schemas,
    ...employeePortal.Announcements.schemas,
    ...employeePortal.Links.schemas,
    ...employeePortal.Invitations.schemas,
    ...employeePortal.Schedules.schemas,
    ...employeePortal.Shifts.schemas,
    ...employeePortal.Payments.schemas,
    ...employeePortal.Overtimes.schemas,
    ...employeePortal.ConfigurationTemplates.schemas,
    ...employeePortal.InvoiceList.schemas,
    ...employeePortal.Accounts.schemas,
    ...employeePortal.Services.schemas,
    ...employeePortal.VacationList.schemas,
    ...employeePortal.VacationRequests.schemas,
    ...employeePortal.VacationTypes.schemas,
    ...employeePortal.Onboarding.schemas,
    ...employeePortal.Offboarding.schemas,
    ...employeePortal.Missions.schemas,
    ...employeePortal.Activity.schemas,
    ...employeePortal.Departments.schemas,
    ...employeePortal.JobTypes.schemas,
    ...employeePortal.Reporting.schemas,
    // crm schemas
    ...crm.Campaigns.schemas,
    ...crm.Leads.schemas,
    ...crm.Customers.schemas,
    ...crm.Deals.schemas,
    ...crm.Orders.schemas,
    ...crm.Products.schemas,
    ...crm.Activities.schemas,
    ...crm.ContactCampaign.schemas,
    ...crm.Carriers.schemas,
    ...crm.Channels.schemas,
    ...crm.DealStages.schemas,
    ...crm.DealTypes.schemas,
    ...crm.ContactSources.schemas,
    ...crm.LeadStatuses.schemas,
    ...crm.ActivityPurposes.schemas,
    ...crm.BusinessCategories.schemas,
    ...crm.ProductCategories.schemas,
    ...crm.ContactField.schemas,
    ...crm.OrderField.schemas,
    ...crm.DealField.schemas,
    ...crm.ProductField.schemas,
    ...crm.CampaignField.schemas,
    // monitoring schemas (for now its temporary commented)
    // ...monitoring.AgentTimeReport.schemas,
    // ...monitoring.RecordingVoices.schemas,
    // pbx schemas
    ...pbx.UserPhones.schemas,
    ...pbx.OrganizationalPhones.schemas,
    ...pbx.VoicemailMessages.schemas,
    ...pbx.VoicemailBoxes.schemas,
    ...pbx.AudioStore.schemas,
    ...pbx.ListQueues.schemas,
    ...pbx.ListWorkspaceQueues.schemas,
    ...pbx.ListDialerQueues.schemas,
    ...pbx.ListDIDs.schemas,
    ...pbx.DIDOrders.schemas,
    ...pbx.AddressBook.schemas,
    ...pbx.Recordings.schemas,
    ...pbx.CallLogs.schemas,
    ...pbx.MessageLogs.schemas,
    ...pbx.CallMonitoring.schemas,
    ...pbx.IPSecurity.schemas,
    ...pbx.MyCampaigns.schemas,
    ...pbx.OrganisationCampaigns.schemas,
    ...pbx.UserCampaigns.schemas,
    ...pbx.MyDNCProfiles.schemas,
    ...pbx.OrganizationDNCProfiles.schemas,
    ...pbx.UserDNCProfiles.schemas,
    ...pbx.OmniChannels.schemas,

    // Workspace Configurations
    ...worspaceConfiguration.QueueConfigurations.schemas,
    ...worspaceConfiguration.DispositionStatus.schemas,
    ...worspaceConfiguration.Workspaces.schemas,
    ...worspaceConfiguration.Webhooks.schemas,
  },
  paths: {
    // backoffice apis
    // ...backoffice.Auth.apis,
    ...backoffice.ClientUser.apis,
    ...backoffice.UserGroup.apias,
    ...backoffice.Role.apis,
    ...backoffice.MailingConfiguration.apis,
    ...backoffice.UserSelf.apis,
    // switch apis
    ...switchModule.MyAccount.apis,
    ...switchModule.CallLogs.apis,
    ...switchModule.MessageLogs.apis,
    ...switchModule.InternalGateways.apis,
    // employee-portal apis
    ...employeePortal.MyAccount.apis,
    ...employeePortal.Employees.apis,
    ...employeePortal.Announcements.apis,
    ...employeePortal.Links.apis,
    ...employeePortal.Invitations.apis,
    ...employeePortal.Schedules.apis,
    ...employeePortal.Shifts.apis,
    ...employeePortal.Payments.apis,
    ...employeePortal.Overtimes.apis,
    ...employeePortal.ConfigurationTemplates.apis,
    ...employeePortal.InvoiceList.apis,
    ...employeePortal.Accounts.apis,
    ...employeePortal.Services.apis,
    ...employeePortal.VacationList.apis,
    ...employeePortal.VacationRequests.apis,
    ...employeePortal.VacationTypes.apis,
    ...employeePortal.Onboarding.apis,
    ...employeePortal.Offboarding.apis,
    ...employeePortal.Missions.apis,
    ...employeePortal.Activity.apis,
    ...employeePortal.Departments.apis,
    ...employeePortal.JobTypes.apis,
    ...employeePortal.Reporting.apis,
    // crm apis
    ...crm.Campaigns.apis,
    ...crm.Leads.apis,
    ...crm.Customers.apis,
    ...crm.Deals.apis,
    ...crm.Orders.apis,
    ...crm.Products.apis,
    ...crm.Activities.apis,
    ...crm.ContactCampaign.apis,
    ...crm.Carriers.apis,
    ...crm.Channels.apis,
    ...crm.DealStages.apis,
    ...crm.DealTypes.apis,
    ...crm.ContactSources.apis,
    ...crm.LeadStatuses.apis,
    ...crm.ActivityPurposes.apis,
    ...crm.BusinessCategories.apis,
    ...crm.ProductCategories.apis,
    ...crm.ContactField.apis,
    ...crm.OrderField.apis,
    ...crm.DealField.apis,
    ...crm.ProductField.apis,
    ...crm.CampaignField.apis,
    // monitoring apis (for now its temporary commented)
    // ...monitoring.AgentTimeReport.apis,
    // ...monitoring.RecordingVoices.apis,
    // pbx apis
    ...pbx.UserPhones.apis,
    ...pbx.OrganizationalPhones.apis,
    ...pbx.VoicemailMessages.apis,
    ...pbx.VoicemailBoxes.apis,
    ...pbx.AudioStore.apis,
    ...pbx.ListQueues.apis,
    ...pbx.ListWorkspaceQueues.apis,
    ...pbx.ListDialerQueues.apis,
    ...pbx.ListDIDs.apis,
    ...pbx.DIDOrders.apis,
    ...pbx.AddressBook.apis,
    ...pbx.Recordings.apis,
    ...pbx.CallLogs.apis,
    ...pbx.MessageLogs.apis,
    ...pbx.CallMonitoring.apis,
    ...pbx.IPSecurity.apis,
    ...pbx.MyCampaigns.apis,
    ...pbx.OrganisationCampaigns.apis,
    ...pbx.MyDNCProfiles.apis,
    ...pbx.UserCampaigns.apis,
    ...pbx.OrganizationDNCProfiles.apis,
    ...pbx.UserDNCProfiles.apis,
    ...pbx.OmniChannels.apis,

    // Workspace Configurations
    ...worspaceConfiguration.QueueConfigurations.apis,
    ...worspaceConfiguration.DispositionStatus.apis,
    ...worspaceConfiguration.Workspaces.apis,
    ...worspaceConfiguration.Webhooks.apis,
  },
  requestBodies: {
    // backoffice body
    // ...backoffice.Auth.body,
    ...backoffice.ClientUser.body,
    ...backoffice.UserGroup.body,
    ...backoffice.Role.body,
    ...backoffice.MailingConfiguration.body,
    ...backoffice.UserSelf.body,
    // switch body
    ...switchModule.MyAccount.body,
    ...switchModule.CallLogs.body,
    ...switchModule.MessageLogs.body,
    ...switchModule.InternalGateways.body,
    // employee-portal body
    ...employeePortal.MyAccount.body,
    ...employeePortal.Employees.body,
    ...employeePortal.Announcements.body,
    ...employeePortal.Links.body,
    ...employeePortal.Invitations.body,
    ...employeePortal.Schedules.body,
    ...employeePortal.Shifts.body,
    ...employeePortal.Payments.body,
    ...employeePortal.Overtimes.body,
    ...employeePortal.ConfigurationTemplates.body,
    ...employeePortal.InvoiceList.body,
    ...employeePortal.Accounts.body,
    ...employeePortal.Services.body,
    ...employeePortal.VacationList.body,
    ...employeePortal.VacationRequests.body,
    ...employeePortal.VacationTypes.body,
    ...employeePortal.Onboarding.body,
    ...employeePortal.Offboarding.body,
    ...employeePortal.Missions.body,
    ...employeePortal.Activity.body,
    ...employeePortal.Departments.body,
    ...employeePortal.JobTypes.body,
    ...employeePortal.Reporting.body,
    // crm body
    ...crm.Campaigns.body,
    ...crm.Leads.body,
    ...crm.Customers.body,
    ...crm.Deals.body,
    ...crm.Orders.body,
    ...crm.Products.body,
    ...crm.Activities.body,
    ...crm.ContactCampaign.body,
    ...crm.Carriers.body,
    ...crm.Channels.body,
    ...crm.DealStages.body,
    ...crm.DealTypes.body,
    ...crm.ContactSources.body,
    ...crm.LeadStatuses.body,
    ...crm.ActivityPurposes.body,
    ...crm.BusinessCategories.body,
    ...crm.ProductCategories.body,
    ...crm.ContactField.body,
    ...crm.OrderField.body,
    ...crm.DealField.body,
    ...crm.ProductField.body,
    ...crm.CampaignField.body,
    // monitoring body (for now its temporary commented)
    // ...monitoring.AgentTimeReport.body,
    // ...monitoring.RecordingVoices.body,
    // pbx body
    ...pbx.UserPhones.body,
    ...pbx.OrganizationalPhones.body,
    ...pbx.VoicemailMessages.body,
    ...pbx.VoicemailBoxes.body,
    ...pbx.AudioStore.body,
    ...pbx.ListQueues.body,
    ...pbx.ListWorkspaceQueues.body,
    ...pbx.ListDialerQueues.body,
    ...pbx.ListDIDs.body,
    ...pbx.DIDOrders.body,
    ...pbx.AddressBook.body,
    ...pbx.Recordings.body,
    ...pbx.CallLogs.body,
    ...pbx.MessageLogs.body,
    ...pbx.CallMonitoring.body,
    ...pbx.IPSecurity.body,
    ...pbx.MyCampaigns.body,
    ...pbx.OrganisationCampaigns.body,
    ...pbx.UserCampaigns.body,
    ...pbx.MyDNCProfiles.body,
    ...pbx.OrganizationDNCProfiles.body,
    ...pbx.UserDNCProfiles.body,
    ...pbx.OmniChannels.body,

    // Workspace Configurations
    ...worspaceConfiguration.QueueConfigurations.body,
    ...worspaceConfiguration.DispositionStatus.body,
    ...worspaceConfiguration.Workspaces.body,
    ...worspaceConfiguration.Webhooks.body,
  },
};
