exports.currency_enum = [
  "AFN",
  "AFA",
  "ALL",
  "ALK",
  "DZD",
  "ADP",
  "AOA",
  "AOK",
  "AON",
  "AOR",
  "ARA",
  "ARS",
  "ARM",
  "ARP",
  "ARL",
  "AMD",
  "AWG",
  "AUD",
  "ATS",
  "AZN",
  "AZM",
  "BSD",
  "BHD",
  "BDT",
  "BBD",
  "BYN",
  "BYB",
  "BYR",
  "BEF",
  "BEC",
  "BEL",
  "BZD",
  "BMD",
  "BTN",
  "VED",
  "BOB",
  "BOL",
  "BOV",
  "BOP",
  "BAM",
  "BAD",
  "BAN",
  "BWP",
  "BRC",
  "BRZ",
  "BRE",
  "BRR",
  "BRN",
  "BRB",
  "BRL",
  "GBP",
  "BND",
  "BGL",
  "BGN",
  "BGO",
  "BGM",
  "BUK",
  "BIF",
  "KHR",
  "CAD",
  "CVE",
  "KYD",
  "XAF",
  "XPF",
  "CLE",
  "CLP",
  "CLF",
  "CNX",
  "CNY",
  "CNH",
  "COP",
  "COU",
  "KMF",
  "CDF",
  "CRC",
  "HRD",
  "HRK",
  "CUC",
  "CUP",
  "CYP",
  "CZK",
  "CSK",
  "DKK",
  "DJF",
  "DOP",
  "NLG",
  "XCD",
  "DDM",
  "ECS",
  "ECV",
  "EGP",
  "GQE",
  "ERN",
  "EEK",
  "ETB",
  "EUR",
  "XEU",
  "FKP",
  "FJD",
  "FIM",
  "FRF",
  "XFO",
  "XFU",
  "GMD",
  "GEK",
  "GEL",
  "DEM",
  "GHS",
  "GHC",
  "GIP",
  "GRD",
  "GTQ",
  "GWP",
  "GNF",
  "GNS",
  "GYD",
  "HTG",
  "HNL",
  "HKD",
  "HUF",
  "ISK",
  "ISJ",
  "INR",
  "IDR",
  "IRR",
  "IQD",
  "IEP",
  "ILS",
  "ILP",
  "ILR",
  "ITL",
  "JMD",
  "JPY",
  "JOD",
  "KZT",
  "KES",
  "KWD",
  "KGS",
  "LAK",
  "LVL",
  "LVR",
  "LBP",
  "LSL",
  "LRD",
  "LYD",
  "LTL",
  "LTT",
  "LUL",
  "LUC",
  "LUF",
  "MOP",
  "MKD",
  "MKN",
  "MGA",
  "MGF",
  "MWK",
  "MYR",
  "MVR",
  "MVP",
  "MLF",
  "MTL",
  "MTP",
  "MRU",
  "MRO",
  "MUR",
  "MXV",
  "MXN",
  "MXP",
  "MDC",
  "MDL",
  "MCF",
  "MNT",
  "MAD",
  "MAF",
  "MZE",
  "MZN",
  "MZM",
  "MMK",
  "NAD",
  "NPR",
  "ANG",
  "TWD",
  "NZD",
  "NIO",
  "NIC",
  "NGN",
  "KPW",
  "NOK",
  "OMR",
  "PKR",
  "PAB",
  "PGK",
  "PYG",
  "PEI",
  "PEN",
  "PES",
  "PHP",
  "PLN",
  "PLZ",
  "PTE",
  "GWE",
  "QAR",
  "RHD",
  "XRE",
  "RON",
  "ROL",
  "RUB",
  "RUR",
  "RWF",
  "SVC",
  "WST",
  "STN",
  "STD",
  "SAR",
  "RSD",
  "CSD",
  "SCR",
  "SLL",
  "SLE",
  "SGD",
  "SKK",
  "SIT",
  "SBD",
  "SOS",
  "ZAR",
  "ZAL",
  "KRH",
  "KRW",
  "KRO",
  "SSP",
  "SUR",
  "ESP",
  "ESA",
  "ESB",
  "LKR",
  "SHP",
  "SDD",
  "SDG",
  "SDP",
  "SRD",
  "SRG",
  "SZL",
  "SEK",
  "CHF",
  "SYP",
  "TJR",
  "TJS",
  "TZS",
  "THB",
  "TPE",
  "TOP",
  "TTD",
  "TND",
  "TRY",
  "TRL",
  "TMT",
  "TMM",
  "UGX",
  "UGS",
  "UAH",
  "UAK",
  "AED",
  "UYW",
  "UYU",
  "UYP",
  "UYI",
  "USD",
  "USN",
  "USS",
  "UZS",
  "VUV",
  "VES",
  "VEB",
  "VEF",
  "VND",
  "VNN",
  "XOF",
  "CHE",
  "CHW",
  "YDD",
  "YER",
  "YUN",
  "YUD",
  "YUM",
  "YUR",
  "ZRN",
  "ZRZ",
  "ZMW",
  "ZMK",
  "ZWD",
  "ZWR",
  "ZWL",
];

exports.currency_enum_titles = [
  "Afghan Afghani",
  "Afghan Afghani (1927–2002)",
  "Albanian Lek",
  "Albanian Lek (1946–1965)",
  "Algerian Dinar",
  "Andorran Peseta",
  "Angolan Kwanza",
  "Angolan Kwanza (1977–1991)",
  "Angolan New Kwanza (1990–2000)",
  "Angolan Readjusted Kwanza (1995–1999)",
  "Argentine Austral",
  "Argentine Peso",
  "Argentine Peso (1881–1970)",
  "Argentine Peso (1983–1985)",
  "Argentine Peso Ley (1970–1983)",
  "Armenian Dram",
  "Aruban Florin",
  "Australian Dollar",
  "Austrian Schilling",
  "Azerbaijani Manat",
  "Azerbaijani Manat (1993–2006)",
  "Bahamian Dollar",
  "Bahraini Dinar",
  "Bangladeshi Taka",
  "Barbadian Dollar",
  "Belarusian Ruble",
  "Belarusian Ruble (1994–1999)",
  "Belarusian Ruble (2000–2016)",
  "Belgian Franc",
  "Belgian Franc (convertible)",
  "Belgian Franc (financial)",
  "Belize Dollar",
  "Bermudan Dollar",
  "Bhutanese Ngultrum",
  "Bolívar Soberano",
  "Bolivian Boliviano",
  "Bolivian Boliviano (1863–1963)",
  "Bolivian Mvdol",
  "Bolivian Peso",
  "Bosnia-Herzegovina Convertible Mark",
  "Bosnia-Herzegovina Dinar (1992–1994)",
  "Bosnia-Herzegovina New Dinar (1994–1997)",
  "Botswanan Pula",
  "Brazilian Cruzado (1986–1989)",
  "Brazilian Cruzeiro (1942–1967)",
  "Brazilian Cruzeiro (1990–1993)",
  "Brazilian Cruzeiro (1993–1994)",
  "Brazilian New Cruzado (1989–1990)",
  "Brazilian New Cruzeiro (1967–1986)",
  "Brazilian Real",
  "British Pound",
  "Brunei Dollar",
  "Bulgarian Hard Lev",
  "Bulgarian Lev",
  "Bulgarian Lev (1879–1952)",
  "Bulgarian Socialist Lev",
  "Burmese Kyat",
  "Burundian Franc",
  "Cambodian Riel",
  "Canadian Dollar",
  "Cape Verdean Escudo",
  "Cayman Islands Dollar",
  "Central African CFA Franc",
  "CFP Franc",
  "Chilean Escudo",
  "Chilean Peso",
  "Chilean Unit of Account (UF)",
  "Chinese People’s Bank Dollar",
  "Chinese Yuan",
  "Chinese Yuan (offshore)",
  "Colombian Peso",
  "Colombian Real Value Unit",
  "Comorian Franc",
  "Congolese Franc",
  "Costa Rican Colón",
  "Croatian Dinar",
  "Croatian Kuna",
  "Cuban Convertible Peso",
  "Cuban Peso",
  "Cypriot Pound",
  "Czech Koruna",
  "Czechoslovak Hard Koruna",
  "Danish Krone",
  "Djiboutian Franc",
  "Dominican Peso",
  "Dutch Guilder",
  "East Caribbean Dollar",
  "East German Mark",
  "Ecuadorian Sucre",
  "Ecuadorian Unit of Constant Value",
  "Egyptian Pound",
  "Equatorial Guinean Ekwele",
  "Eritrean Nakfa",
  "Estonian Kroon",
  "Ethiopian Birr",
  "Euro",
  "European Currency Unit",
  "Falkland Islands Pound",
  "Fijian Dollar",
  "Finnish Markka",
  "French Franc",
  "French Gold Franc",
  "French UIC-Franc",
  "Gambian Dalasi",
  "Georgian Kupon Larit",
  "Georgian Lari",
  "German Mark",
  "Ghanaian Cedi",
  "Ghanaian Cedi (1979–2007)",
  "Gibraltar Pound",
  "Greek Drachma",
  "Guatemalan Quetzal",
  "Guinea-Bissau Peso",
  "Guinean Franc",
  "Guinean Syli",
  "Guyanaese Dollar",
  "Haitian Gourde",
  "Honduran Lempira",
  "Hong Kong Dollar",
  "Hungarian Forint",
  "Icelandic Króna",
  "Icelandic Króna (1918–1981)",
  "Indian Rupee",
  "Indonesian Rupiah",
  "Iranian Rial",
  "Iraqi Dinar",
  "Irish Pound",
  "Israeli New Shekel",
  "Israeli Pound",
  "Israeli Shekel (1980–1985)",
  "Italian Lira",
  "Jamaican Dollar",
  "Japanese Yen",
  "Jordanian Dinar",
  "Kazakhstani Tenge",
  "Kenyan Shilling",
  "Kuwaiti Dinar",
  "Kyrgystani Som",
  "Laotian Kip",
  "Latvian Lats",
  "Latvian Ruble",
  "Lebanese Pound",
  "Lesotho Loti",
  "Liberian Dollar",
  "Libyan Dinar",
  "Lithuanian Litas",
  "Lithuanian Talonas",
  "Luxembourg Financial Franc",
  "Luxembourgian Convertible Franc",
  "Luxembourgian Franc",
  "Macanese Pataca",
  "Macedonian Denar",
  "Macedonian Denar (1992–1993)",
  "Malagasy Ariary",
  "Malagasy Franc",
  "Malawian Kwacha",
  "Malaysian Ringgit",
  "Maldivian Rufiyaa",
  "Maldivian Rupee (1947–1981)",
  "Malian Franc",
  "Maltese Lira",
  "Maltese Pound",
  "Mauritanian Ouguiya",
  "Mauritanian Ouguiya (1973–2017)",
  "Mauritian Rupee",
  "Mexican Investment Unit",
  "Mexican Peso",
  "Mexican Silver Peso (1861–1992)",
  "Moldovan Cupon",
  "Moldovan Leu",
  "Monegasque Franc",
  "Mongolian Tugrik",
  "Moroccan Dirham",
  "Moroccan Franc",
  "Mozambican Escudo",
  "Mozambican Metical",
  "Mozambican Metical (1980–2006)",
  "Myanmar Kyat",
  "Namibian Dollar",
  "Nepalese Rupee",
  "Netherlands Antillean Guilder",
  "New Taiwan Dollar",
  "New Zealand Dollar",
  "Nicaraguan Córdoba",
  "Nicaraguan Córdoba (1988–1991)",
  "Nigerian Naira",
  "North Korean Won",
  "Norwegian Krone",
  "Omani Rial",
  "Pakistani Rupee",
  "Panamanian Balboa",
  "Papua New Guinean Kina",
  "Paraguayan Guarani",
  "Peruvian Inti",
  "Peruvian Sol",
  "Peruvian Sol (1863–1965)",
  "Philippine Peso",
  "Polish Zloty",
  "Polish Zloty (1950–1995)",
  "Portuguese Escudo",
  "Portuguese Guinea Escudo",
  "Qatari Rial",
  "Rhodesian Dollar",
  "RINET Funds",
  "Romanian Leu",
  "Romanian Leu (1952–2006)",
  "Russian Ruble",
  "Russian Ruble (1991–1998)",
  "Rwandan Franc",
  "Salvadoran Colón",
  "Samoan Tala",
  "São Tomé & Príncipe Dobra",
  "São Tomé & Príncipe Dobra (1977–2017)",
  "Saudi Riyal",
  "Serbian Dinar",
  "Serbian Dinar (2002–2006)",
  "Seychellois Rupee",
  "Sierra Leonean Leone",
  "Sierra Leonean New Leone",
  "Singapore Dollar",
  "Slovak Koruna",
  "Slovenian Tolar",
  "Solomon Islands Dollar",
  "Somali Shilling",
  "South African Rand",
  "South African Rand (financial)",
  "South Korean Hwan (1953–1962)",
  "South Korean Won",
  "South Korean Won (1945–1953)",
  "South Sudanese Pound",
  "Soviet Rouble",
  "Spanish Peseta",
  "Spanish Peseta (A account)",
  "Spanish Peseta (convertible account)",
  "Sri Lankan Rupee",
  "St. Helena Pound",
  "Sudanese Dinar (1992–2007)",
  "Sudanese Pound",
  "Sudanese Pound (1957–1998)",
  "Surinamese Dollar",
  "Surinamese Guilder",
  "Swazi Lilangeni",
  "Swedish Krona",
  "Swiss Franc",
  "Syrian Pound",
  "Tajikistani Ruble",
  "Tajikistani Somoni",
  "Tanzanian Shilling",
  "Thai Baht",
  "Timorese Escudo",
  "Tongan Paʻanga",
  "Trinidad & Tobago Dollar",
  "Tunisian Dinar",
  "Turkish Lira",
  "Turkish Lira (1922–2005)",
  "Turkmenistani Manat",
  "Turkmenistani Manat (1993–2009)",
  "Ugandan Shilling",
  "Ugandan Shilling (1966–1987)",
  "Ukrainian Hryvnia",
  "Ukrainian Karbovanets",
  "United Arab Emirates Dirham",
  "Uruguayan Nominal Wage Index Unit",
  "Uruguayan Peso",
  "Uruguayan Peso (1975–1993)",
  "Uruguayan Peso (Indexed Units)",
  "US Dollar",
  "US Dollar (Next day)",
  "US Dollar (Same day)",
  "Uzbekistani Som",
  "Vanuatu Vatu",
  "Venezuelan Bolívar",
  "Venezuelan Bolívar (1871–2008)",
  "Venezuelan Bolívar (2008–2018)",
  "Vietnamese Dong",
  "Vietnamese Dong (1978–1985)",
  "West African CFA Franc",
  "WIR Euro",
  "WIR Franc",
  "Yemeni Dinar",
  "Yemeni Rial",
  "Yugoslavian Convertible Dinar (1990–1992)",
  "Yugoslavian Hard Dinar (1966–1990)",
  "Yugoslavian New Dinar (1994–2002)",
  "Yugoslavian Reformed Dinar (1992–1993)",
  "Zairean New Zaire (1993–1998)",
  "Zairean Zaire (1971–1993)",
  "Zambian Kwacha",
  "Zambian Kwacha (1968–2012)",
  "Zimbabwean Dollar (1980–2008)",
  "Zimbabwean Dollar (2008)",
  "Zimbabwean Dollar (2009)",
];
