exports.employee_enum = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
];

exports.employee_enum_titles = [
  "sergey (sergey)",
  "Melih (melih)",
  "Billy (billy)",
  "Bari Okan Dogan (bari)",
  "Mikhail (mikhail)",
  "Vince (vince)",
  "Michael1 (michael)",
  "Ryan (ryan)",
  "Faruk (faruk)",
  "Linda Spione (Linda)",
  "John (staff_user)",
  "employee23 (employee23)",
  "Sergey (no_acis_on_ws_user)",
  "Sergey1 (sergey1)",
  "Melih - 2 (melih2)",
  " (disabled1__)",
  " (disabled2)",
  " (disabled3)",
  "Mustafa (mstf)",
  " (created_by_client_admin)",
  " (demo_client_2_staff_manager_1)",
  "SERGEY GRECHIN (staff_manager_with_access_to_sergey_sandbox_only)",
  " (test_userxxx)",
  "Janella (janella)",
  " (demo_client_2_client_manager_3)",
  "Vincent (vincent)",
  " (demo_client_2_client_manager_1)",
  "Jess (jess)",
  "Dexter (dexter)",
  " (demo_client_2_client_manager_admin_1)",
  "ConneXio (ConneXio)",
  "ConneXio (ConneXio Cloud)",
  " (demo_client_2_client_employee_2)",
  "Trisha Ampil (Trisha)",
  " (registered_through_invitation)",
  "John (johnlu)",
  "test (testtest)",
  " (demo_client_2_client_employee_3)",
  "John (john)",
  "Himanshu The First (himanshu1)",
  "Himanshu The Second (himanshu2)",
  "Sergey 2 (sergey2)",
  "dsfsadfsdaf (someuser)",
  "John 1 (john1)",
  " (john2)",
  "john (employee)",
  "netweb (Net web)",
  "netweb (net web n)",
  "bggg (bgfhf)",
  "NetWeb (Net  Web1)",
  "deleteeasd (deleteuser)",
];

exports.employee_funnel_enum = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "9",
  "10",
  "20",
];
exports.employee_funnel_enum_titles = [
  "dddd",
  "things to do when onboarding",
  "Client Onboarding",
  "gggggg",
  "sfasdfasf",
  "vvvvvv",
  "ffffff",
  "test",
  "Sample Test",
  "demo funnel",
];
