exports.user_group_roles_enum = [
  "6",
  "7",
  "14",
  "15",
  "18",
  "19",
  "20",
  "21",
  "22",
  "29",
  "30",
  "36",
  "37",
];

exports.user_group_roles_enum_titles = [
  "employee role",
  "admin",
  "Sales",
  "no acis on WS",
  "DEMO_CLIENT_2_CLIENT_EMPLOYEE",
  "DEMO_CLIENT_2_CLIENT_EMPLOYEE_ADMIN",
  "DEMO_CLIENT_2_CLIENT_MANAGER",
  "DEMO_CLIENT_2_CLIENT_MANAGER_ADMIN",
  "___DEMO_CLIENT_2_STAFF_MANAGER",
  "CREATED_BY_CLIENT_ADMIN",
  "CREATED_BY_LIMITED_STAFF_USER",
  "Customer Service",
  "Sales Reps",
];
